using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Reflection;
using System.Runtime.InteropServices;
using AnoMech.Helpers;
using AnoMech.Pointers;
using Dalamud.Game.Addon.Lifecycle;
using Dalamud.Game.Addon.Lifecycle.AddonArgTypes;
using Dalamud.Game.ClientState.Conditions;
using Dalamud.Hooking;
using FFXIVClientStructs.FFXIV.Client.Game;
using FFXIVClientStructs.FFXIV.Client.Game.Character;
using FFXIVClientStructs.FFXIV.Client.Game.Event;
using FFXIVClientStructs.FFXIV.Client.Game.UI;
using FFXIVClientStructs.FFXIV.Client.Graphics.Environment;
using FFXIVClientStructs.FFXIV.Client.Network;
using FFXIVClientStructs.FFXIV.Client.UI.Agent;
using Lumina.Excel.Sheets;
using static FFXIVClientStructs.FFXIV.Client.Network.PacketDispatcher.Delegates;
using ThreadingTask = System.Threading.Tasks.Task;

namespace AnoMech.Core.Map;

// Client-side zone loading and packet firewall. Ported from Hyperborea (Memory.cs
// + Utils.cs). Must be in the Inn before calling Enter(); Leave() reloads the inn.
// All public methods must be called from the framework thread.
public sealed unsafe class ZoneSession : IDisposable
{
    private class SessionSave
    {
        public uint TerritoryId { get; set; }
        public Vector3 Position { get; set; }
        public float Rotation { get; set; }
        public int Exp { get; set; }
        public uint RestedExp { get; set; }
        public bool LevelSync { get; set; }
        public int Level { get; set; }
        public bool ItemLevelSync { get; set; }
        public Dictionary<int, int> Attributes { get; } = new();
    }

    // TerritoryIntendedUse.Inn = 2 (from ECommons TerritoryIntendedUseEnum)
    private const uint InnIntendedUse = 2;

    // ── Native delegates ──────────────────────────────────────────────────────

    private delegate byte SendPacketDelegate(nint a1, nint a2, nint a3, byte a4);
    private readonly Hook<SendPacketDelegate> sendPacketHook;

    // OnReceivePacket delegate type generated by FFXIVClientStructs from [VirtualFunction(1)]
    private readonly Hook<OnReceivePacket> receivePacketHook;

    // ── State ─────────────────────────────────────────────────────────────────

    private readonly ushort heartbeatOpcode;
    private uint? loadedInstanceContent;

    // Set true right before we open the Social window for a party resync; the Social
    // PostSetup listener closes it again and clears this. Distinguishes our open from
    // a manual one so manual opens aren't auto-closed.
    private bool autoCloseSocial;

    public bool IsActive { get; private set; }

    private readonly SessionSave sessionSave = new();

    // ── Construction ──────────────────────────────────────────────────────────

    public ZoneSession()
    {
        // Heartbeat (ZoneUp) opcode — auto-detected by signature (from Hyperborea Memory.cs)
        heartbeatOpcode = (ushort)Marshal.ReadInt32(
            Plugin.SigScanner.ScanText("C7 44 24 ?? ?? ?? ?? ?? 48 F7 F1") + 0x4);
        Plugin.Log.Information($"[ZoneSession] Heartbeat opcode: {heartbeatOpcode}");

        // Send-packet hook (sig from Hyperborea Memory.cs)
        var sendAddr = Plugin.SigScanner.ScanText(
            "48 89 5C 24 ?? 48 89 74 24 ?? 4C 89 64 24 ?? 55 41 56 41 57 48 8B EC 48 83 EC 70");
        sendPacketHook = Plugin.GameInterop.HookFromAddress<SendPacketDelegate>(
            sendAddr, SendPacketDetour);

        // Receive-packet hook — address from PacketDispatcher.StaticVirtualTablePointer->OnReceivePacket.
        // This is the standard approach used by ECommons/Dalamud's GameNetwork service.
        // PacketDispatcher.Delegates.OnReceivePacket and StaticVirtualTablePointer are generated by
        // FFXIVClientStructs from [VirtualFunction(1)] + [VirtualTable] on PacketDispatcher.
        var receiveAddr = (nint)PacketDispatcher.StaticVirtualTablePointer->OnReceivePacket;
        Plugin.Log.Information($"[ZoneSession] OnReceivePacket: {receiveAddr:X}");
        receivePacketHook = Plugin.GameInterop.HookFromAddress<OnReceivePacket>(
            receiveAddr, ReceivePacketDetour);

        Plugin.AddonLifecycle.RegisterListener(AddonEvent.PostSetup, "Social", OnSocialPostSetup);

        Plugin.Log.Information("[ZoneSession] Initialized.");
    }

    // ── Public API ────────────────────────────────────────────────────────────

    public static bool IsInInn()
    {
        var row = Plugin.DataManager.GetExcelSheet<TerritoryType>()
            ?.GetRowOrDefault(Plugin.ClientState.TerritoryType);
        return row?.TerritoryIntendedUse.RowId == InnIntendedUse;
    }

    // Any state in which the local player can't freely act. Used as a second
    // gate before starting a scenario from an inn so we don't kick off mid-
    // cutscene, mid-NPC-event, mid-craft, mid-zone, etc.
    public static bool IsPlayerBusy()
    {
        var c = Plugin.Condition;
        return c[ConditionFlag.WatchingCutscene]
            || c[ConditionFlag.WatchingCutscene78]
            || c[ConditionFlag.OccupiedInCutSceneEvent]
            || c[ConditionFlag.OccupiedInEvent]
            || c[ConditionFlag.OccupiedInQuestEvent]
            || c[ConditionFlag.OccupiedSummoningBell]
            || c[ConditionFlag.Occupied30]
            || c[ConditionFlag.Occupied33]
            || c[ConditionFlag.Occupied38]
            || c[ConditionFlag.Occupied39]
            || c[ConditionFlag.Crafting]
            || c[ConditionFlag.ExecutingCraftingAction]
            || c[ConditionFlag.PreparingToCraft]
            || c[ConditionFlag.Gathering]
            || c[ConditionFlag.ExecutingGatheringAction]
            || c[ConditionFlag.Fishing]
            || c[ConditionFlag.TradeOpen]
            || c[ConditionFlag.BetweenAreas]
            || c[ConditionFlag.LoggingOut]
            || c[ConditionFlag.WaitingForDutyFinder]
            || c[ConditionFlag.InDutyQueue]
            || c[ConditionFlag.InCombat]
            || c[ConditionFlag.Mounted]
            || c[ConditionFlag.Jumping]
            || c[ConditionFlag.Occupied];
    }

    // Load the target territory, teleport player to playerSpawn, enable firewall.
    // Firewall is enabled before the zone load (matching Hyperborea's sequence).
    public void Enter(uint territoryId, Vector3 playerSpawn, byte levelSync, ushort itemLevelSync)
    {
        var localPlayer = Plugin.ObjectTable.LocalPlayer!;

        sessionSave.TerritoryId = Plugin.ClientState.TerritoryType;
        sessionSave.Position = localPlayer.Position;
        sessionSave.Rotation = localPlayer.Rotation;
        sessionSave.Exp = Plugin.PlayerState.GetClassJobExperience(Plugin.PlayerState.ClassJob.Value);
        sessionSave.RestedExp = Plugin.PlayerState.BaseRestedExperience;
        sessionSave.LevelSync = levelSync != 0;
        sessionSave.Level = localPlayer.Level;
        sessionSave.ItemLevelSync = itemLevelSync != 0;
        sessionSave.Attributes.Clear();

        EnableFirewall();
        LoadZoneInternal(territoryId, false, playerSpawn);
        IsActive = true;
        Plugin.Log.Information($"[ZoneSession] Entered territory {territoryId}.");
    }

    // Immediately set the active weather. Must be called on the framework thread.
    // weatherId is a Weather-sheet row; transition is the fade time in seconds.
    public void SetWeather(byte weatherId, float transition = 0.5f)
    {
        var env = EnvManager.Instance();
        if (env == null) return;
        env->ActiveWeather = weatherId;
        env->TransitionTime = transition;
    }

    // Reload the saved inn territory and restore position; disable firewall.
    public void Revert(bool dispose)
    {
        // We need to wait before calling DisableFirewall(), so we'll set the Occupied condition to be sure the Player doesn't do anything in the meantime. 
        var condition = Conditions.Instance();
        condition->Occupied = true;

        if (sessionSave.TerritoryId != 0)
            LoadZoneInternal(sessionSave.TerritoryId, true, sessionSave.Position, sessionSave.Rotation);

        sessionSave.TerritoryId = 0;

        IsActive = false;
        Plugin.Log.Information("[ZoneSession] Reverted to inn.");

        // If this is getting called on Dispose(), then these Tasks will not be properly executed, so we'll gate them to be safe
        if (!dispose)
        {
            // If this isn't delayed, a Packet will be sent to the server!!!
            ThreadingTask.Delay(1000).ContinueWith(_ =>
            {
                // The Player could do something like jump, so to be extremely sure we are where we are supposed to, we set the Position and Rotation again.
                SetLocalPlayerPosition(sessionSave.Position, sessionSave.Rotation);
                condition->Occupied = false;

                // TODO: this is here because of Suppression. Either define it as normal behaviour, or add an OnLeave method on Scenarios
                condition->SufferingStatusAffliction = false;
                condition->SufferingStatusAffliction2 = false;

                if (Plugin.ObjectTable.LocalPlayer != null)
                {
                    AnoMech.Pointers.PacketDispatcherPointers.HandleActorControlPacket(Plugin.ObjectTable.LocalPlayer.EntityId, 54, 1, 0, 0, 0, 0, 0, 0, 0, 0xE0000000, false);
                }

                DisableFirewall();
            });

            // Resync the real party HUD once the inn reload has settled. A bare
            // InfoProxyPartyMember.RequestData() sends the same request the Social window
            // does but doesn't sync MainGroup — the HUD update is client-side work the
            // Social agent does on the reply (proven via packet trace). So open the Social
            // agent and let it do that work itself. (Closing it again is a follow-up step.)
            ThreadingTask.Delay(1500).ContinueWith(_ => Plugin.Framework.Run(OpenSocialForPartyResync));
        }
        else
        {
            // This skips all safety delays, so if possible, don't disable the plugin while being in a Scenario
            SetLocalPlayerPosition(sessionSave.Position, sessionSave.Rotation);
            condition->Occupied = false;
            DisableFirewall();
            Plugin.Framework.Run(OpenSocialForPartyResync);
        }
    }

    // Opens the Social agent, which issues its own (callback-routed) party-member
    // request and processes the reply into the party HUD — the step a bare RequestData
    // can't trigger. Firing this from the settled inn state mirrors a manual open.
    private void OpenSocialForPartyResync()
    {
        var am = AgentModule.Instance();
        var social = am != null ? am->GetAgentByInternalId(AgentId.Social) : null;
        if (social == null) return;
        autoCloseSocial = true;
        social->Show();
        Plugin.Log.Information("[ZoneSession] Opened Social for party resync.");
    }

    // Closes the Social window again as soon as it finishes opening — but only when
    // we opened it (autoCloseSocial), so a manual open is left alone.
    private void OnSocialPostSetup(AddonEvent type, AddonArgs args)
    {
        if (!autoCloseSocial) return;
        autoCloseSocial = false;

        var am = AgentModule.Instance();
        var s = am != null ? am->GetAgentByInternalId(AgentId.Social) : null;
        if (s != null) s->Hide();
        Plugin.Log.Information("[ZoneSession] Auto-closed Social after party resync.");
    }

    public void EnableFirewall()
    {
        sendPacketHook.Enable();
        receivePacketHook.Enable();
    }

    public void DisableFirewall()
    {
        sendPacketHook.Disable();
        receivePacketHook.Disable();
    }

    // ── Zone loading sequence (mirrors Hyperborea Utils.LoadZone) ─────────────

    private void LoadZoneInternal(uint territory, bool unloading, Vector3 playerPos, float? rotation = null)
    {
        var eventFramework = EventFramework.Instance();
        var gm = GameMain.Instance();
        Plugin.Log.Information($"[ZoneSession] LoadZone territory={territory} ef={((nint)eventFramework):X} gm={((nint)gm):X}");
        if (eventFramework == null || gm == null)
        {
            Plugin.Log.Error("[ZoneSession] Null singleton — aborting zone load");
            return;
        }

        var player = (Character*)Plugin.ObjectTable.LocalPlayer!.Address;
        if (player == null)
        {
            Plugin.Log.Error("[ZoneSession] Plugin.ObjectTable.LocalPlayer was null.");
        }

        var classJobId = (byte)Plugin.PlayerState.ClassJob.RowId;

        Plugin.Log.Information("[ZoneSession] Step 1: FinalizeInstanceContent");
        if (loadedInstanceContent != null)
        {
            var uiState = UIState.Instance();

            if (uiState != null)
            {
                uiState->DirectorTodo.IsShown = false;
            }

            EventFrameworkPointers.TerminateDirector(eventFramework, 0x80030000 + loadedInstanceContent.Value);
            loadedInstanceContent = null;

            ResetSync(uiState, player, classJobId);
        }

        Plugin.Log.Information("[ZoneSession] Step 2: DisableDraw all objects");
        foreach (var obj in Plugin.ObjectTable)
        {
            if (obj.Address == IntPtr.Zero) continue;
            ((FFXIVClientStructs.FFXIV.Client.Game.Object.GameObject*)obj.Address)->DisableDraw();
        }

        if (!unloading)
        {
            Plugin.Log.Information("[ZoneSession] Step 3: InitDirector");

            var cfc = GetContentFinderCondition(territory)!.Value;

            var contentId = cfc.Content.RowId;
            Plugin.Log.Information($"[ZoneSession] ContentId={contentId}");

            EventFrameworkPointers.InitDirector(eventFramework, 0x80030000 + contentId, contentId, 0);

            loadedInstanceContent = contentId;
            InstanceContentDirectorHelper.SetDutyData(cfc);

            SetSync(cfc, player, territory, classJobId);
        }
        else
        {
            Plugin.Log.Information("[ZoneSession] Step 3: InitDirector (Skipped)");
        }

        Plugin.Log.Information("[ZoneSession] Step 4: LoadZone (native)");
        GameMainPointers.LoadZone(gm, territory, 0, 0, 1, 1);

        Plugin.Log.Information("[ZoneSession] Step 5: SetupTerritoryType");
        eventFramework->SetTerritoryTypeId((ushort)territory);

        Plugin.Log.Information("[ZoneSession] Step 6: SyncClientState");
        SyncClientStateTerritoryType((ushort)territory);

        Plugin.Log.Information("[ZoneSession] Step 7: SetPosition");
        SetLocalPlayerPosition(playerPos, rotation);

        Plugin.Log.Information("[ZoneSession] LoadZone complete");
    }

    private void SetLocalPlayerPosition(Vector3 position, float? rotation = null)
    {
        if (Plugin.ObjectTable.LocalPlayer is { Address: var addr } && addr != IntPtr.Zero)
        {
            var chara = (Character*)addr;
            chara->GameObject.SetPosition(position.X, position.Y, position.Z);

            if (rotation != null)
            {
                chara->GameObject.SetRotation(rotation.Value);
            }
        }
    }

    private ContentFinderCondition? GetContentFinderCondition(uint territoryId)
    {
        var sheet = Plugin.DataManager.GetExcelSheet<TerritoryType>();

        if (sheet == null)
        {
            Plugin.Log.Debug($"[ZoneSession.GetContentFinderCondition] TerritoryType sheet was null.");
            return null;
        }

        var rowRef = sheet[territoryId].ContentFinderCondition;

        if (!rowRef.IsValid)
        {
            Plugin.Log.Debug($"TerritoryType sheet, index {territoryId} does not have a valid ContentFinderCondition reference.");
            return null;
        }

        return rowRef.Value;
    }

    private static void SyncClientStateTerritoryType(ushort territory)
    {
        try
        {
            var type = Plugin.ClientState.GetType();
            var prop = type.GetProperty("TerritoryType",
                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
            if (prop?.CanWrite == true)
            {
                prop.SetValue(Plugin.ClientState, territory);
                return;
            }
            var field = type.GetField("territoryType",
                BindingFlags.NonPublic | BindingFlags.Instance)
                ?? type.GetField("TerritoryType",
                BindingFlags.NonPublic | BindingFlags.Instance);
            field?.SetValue(Plugin.ClientState, territory);
        }
        catch (Exception e)
        {
            Plugin.Log.Warning($"[ZoneSession] Could not sync ClientState.TerritoryType: {e.Message}");
        }
    }

    // (Item) Level Sync
    private void SetSync(ContentFinderCondition cfc, Character* player, uint territory, byte classJobId)
    {
        var cfcLevelSync = cfc.ClassJobLevelSync;

        if (sessionSave.LevelSync)
        {
            var currentLevel = (byte)Plugin.PlayerState.Level;
            var levelSynced = currentLevel > cfcLevelSync;

            if (levelSynced)
            {
                if (player != null)
                {
                    player->Level = cfcLevelSync;
                }

                var updateClassInfoPacket = new UpdateClassInfoPacket
                {
                    ClassJobId = classJobId,
                    CurrentLevel = currentLevel,
                    ClassJobLevel = currentLevel,
                    SyncedLevel = cfcLevelSync,
                    ClassJobExp = 0,
                    BaseRestedExperience = 0
                };

                PacketDispatcherPointers.HandleUpdateClassInfoPacket(0, &updateClassInfoPacket);
            }
        }

        if (sessionSave.ItemLevelSync)
        {
            var uiState = UIState.Instance();
            if (uiState != null)
            {
                var ilvlSync = cfc.ItemLevelSync != 0 ? cfc.ItemLevelSync : cfc.ItemLevelRequired;

                if (ilvlSync != 0)
                {
                    Plugin.Log.Debug($"Setting up iLvl sync to {ilvlSync}");
                    var syncedAttributes = GetSyncedAttributes(cfcLevelSync, ilvlSync);

                    foreach (var (baseParamId, value) in syncedAttributes)
                    {
                        sessionSave.Attributes[baseParamId] = uiState->PlayerState.Attributes[baseParamId];
                        uiState->PlayerState.Attributes[baseParamId] = value;
                    }
                }
            }
        }
    }

    private void ResetSync(UIState* uiState, Character* player, byte classJobId)
    {
        if (sessionSave.LevelSync)
        {
            var updateClassInfoPacket = new UpdateClassInfoPacket
            {
                ClassJobId = classJobId,
                CurrentLevel = (ushort)sessionSave.Level,
                ClassJobLevel = (ushort)sessionSave.Level,
                SyncedLevel = 0,
                ClassJobExp = (ushort)sessionSave.Exp,
                BaseRestedExperience = sessionSave.RestedExp
            };

            PacketDispatcherPointers.HandleUpdateClassInfoPacket(0, &updateClassInfoPacket);

            if (player != null)
            {
                player->Level = (byte)sessionSave.Level;
            }
        }

        if (sessionSave.ItemLevelSync && uiState != null)
        {
            foreach (var (baseParamId, value) in sessionSave.Attributes)
            {
                uiState->PlayerState.Attributes[baseParamId] = value;
            }
        }
    }

    private Dictionary<int, int> GetSyncedAttributes(byte level, ushort ilvl)
    {
        var stats = new Dictionary<int, int>();

        var itemSheet = Plugin.DataManager.GetExcelSheet<Item>();
        var baseParamSheet = Plugin.DataManager.GetExcelSheet<BaseParam>();
        var paramGrowSheet = Plugin.DataManager.GetExcelSheet<ParamGrow>();

        var supportedAttributes = new PlayerAttribute[]
        {
                PlayerAttribute.SkillSpeed,
                PlayerAttribute.SpellSpeed
        };

        foreach (var attribute in supportedAttributes)
        {
            switch (attribute)
            {
                case PlayerAttribute.SkillSpeed:
                case PlayerAttribute.SpellSpeed:
                    stats[(int)attribute] = paramGrowSheet[level].BaseSpeed;
                    break;
                default:
                    continue;
            }
        }

        // Get Item Stats
        var inventoryManager = InventoryManager.Instance();
        var equippedItems = inventoryManager->GetInventoryContainer(InventoryType.EquippedItems);

        for (int i = 0; i < equippedItems->GetSize(); i++)
        {
            var inventoryItem = equippedItems->Items[i];
            var itemId = inventoryItem.ItemId;

            if (itemId == 0)
            {
                continue;
            }

            var item = itemSheet[itemId];
            var itemLevel = item.LevelItem.RowId;
            
            if (item.LevelItem.RowId <= ilvl) // Add it as is if the ilvl is the same or less than sync
            {
                Plugin.Log.Debug($"Item \"{item.Name}\" (ilvl {item.LevelItem.RowId}) fits the ilvl sync requirements.");

                for (int x = 0; x < item.BaseParam.Count; x++)
                {
                    var baseParam = item.BaseParam[x];
                    var baseParamId = (int)baseParam.RowId;

                    if (!supportedAttributes.Contains((PlayerAttribute)baseParamId))
                    {
                        continue;
                    }

                    stats[baseParamId] += item.BaseParamValue[x];
                }

                // Add extra stats
                ApplyExtraStats(stats, GetMateriaStats(inventoryItem));
                ApplyExtraStats(stats, GetMandervilleWeaponStats(inventoryItem));
            }
            else // Calculate the sync value
            {
                var resistanceStats = new Dictionary<int, int>();

                var resistanceSheet = Plugin.DataManager.GetExcelSheet<ResistanceWeaponAdjust>();
                if (resistanceSheet.TryGetRow(itemId, out var _))
                {
                    resistanceStats = GetMateriaStats(inventoryItem);
                }

                var mandervilleStats = GetMandervilleWeaponStats(inventoryItem);

                // Doing this instead of calling ExdModule.GetItemRowById because it's not guaranteed to always return on this frame
                var dummyItem = new byte[0xA0];
                fixed (byte* dummyItemPtr = dummyItem)
                {
                    *(dummyItemPtr + 0x54) = item.BaseParamModifier;
                    *(ushort*)(dummyItemPtr + 0x8A) = ilvl;
                    *(dummyItemPtr + 0x9A) = (byte)item.EquipSlotCategory.RowId;

                    for (int x = 0; x < item.BaseParam.Count; x++)
                    {
                        var baseParam = item.BaseParam[x];
                        var baseParamId = (int)baseParam.RowId;

                        if (!supportedAttributes.Contains((PlayerAttribute)baseParamId))
                        {
                            continue;
                        }

                        var statValue = item.BaseParamValue[x];

                        if (resistanceStats.TryGetValue(baseParamId, out var resistanceStat))
                        {
                            statValue += (short)resistanceStat;
                        }

                        if (mandervilleStats.TryGetValue(baseParamId, out var mandervilleStat))
                        {
                            statValue += (short)mandervilleStat;
                        }

                        var statMaxValue = (int)InventoryItem.GetParameterMaxValue((uint)baseParamId, dummyItemPtr);
                        var syncedValue = int.Min(statValue, statMaxValue);
                        stats[baseParamId] += syncedValue;

                        Plugin.Log.Debug($"Item \"{item.Name}\" (ilvl {item.LevelItem.RowId})'s {(PlayerAttribute)baseParamId} was synced to {syncedValue}");
                    }
                }
            }
        }

        // Get Food Buffs
        var localPlayer = (BattleChara*)Plugin.ObjectTable.LocalPlayer!.Address;

        if (localPlayer != null)
        {
            var statusManager = localPlayer->StatusManager;

            foreach (var status in statusManager.Status)
            {
                var statusId = status.StatusId;

                if (statusId == 0 || statusId != 48)
                {
                    continue;
                }
                
                var hq = status.Param > 10000;
                var foodId = hq ? status.Param - 10000 : status.Param;

                if (!Plugin.DataManager.GetExcelSheet<ItemFood>().TryGetRow((uint)foodId, out var food))
                {
                    continue;
                }
                
                foreach (var bonus in food.Params)
                {
                    var stat = (int)bonus.BaseParam.RowId;
                    
                    if (stat == 0 || !stats.ContainsKey(stat))
                    {
                        continue;
                    }

                    var value = hq ? bonus.ValueHQ : bonus.Value;
                    var max = hq ? bonus.MaxHQ : bonus.Max;
                    int statBuff;

                    if (bonus.IsRelative)
                    {
                        var currentStat = stats[stat];
                        var percentBuff = (int)(currentStat * (value / 100f));
                        statBuff = int.Min(percentBuff, max);
                    }
                    else
                    {
                        statBuff = value;
                    }

                    stats[stat] += statBuff;
                }
            }
        }

        return stats;
    }

    // This also works for Resistance Weapons
    private Dictionary<int, int> GetMateriaStats(InventoryItem inventoryItem)
    {
        var stats = new Dictionary<int, int>();
        var materiaSheet = Plugin.DataManager.GetExcelSheet<Materia>();

        for (int i = 0; i < inventoryItem.Materia.Length; i++)
        {
            var materiaId = inventoryItem.Materia[i];

            if (materiaId == 0 || !materiaSheet.TryGetRow(materiaId, out var materiaRow))
            {
                continue;
            }

            var index = inventoryItem.MateriaGrades[i];
            var statValue = materiaRow.Value[index];
            var stat = materiaRow.BaseParam.RowId;
            stats[(int)stat] = statValue;
        }

        return stats;
    }

    // https://github.com/VioletStardustXIV/XivGearExport/blob/main/XivGearExport/XivGearSet.cs#L447
    private Dictionary<int, int> GetMandervilleWeaponStats(InventoryItem inventoryItem)
    {
        var stats = new Dictionary<int, int>();

        var statsSheet = Plugin.DataManager.GetExcelSheet<MandervilleWeaponEnhance>();
        var materiaSheet = Plugin.DataManager.GetExcelSheet<Materia>();

        if (!statsSheet.TryGetRow(inventoryItem.ItemId, out var _))
        {
            return stats;
        }

        for (int i = 0; i < inventoryItem.Materia.Length; i++)
        {
            var materiaId = inventoryItem.Materia[i];

            if (materiaId == 0 || !materiaSheet.TryGetRow(materiaId, out var materiaRow))
            {
                continue;
            }

            var index = inventoryItem.MateriaGrades[i];
            var statValue = materiaRow.Value[index];

            switch (materiaId)
            {
                case 1403:
                    stats[(int)PlayerAttribute.CriticalHit] = statValue;
                    break;
                case 1404:
                    stats[(int)PlayerAttribute.DirectHitRate] = statValue;
                    break;
                case 1405:
                    stats[(int)PlayerAttribute.Determination] = statValue;
                    break;
                case 1406:
                    stats[(int)PlayerAttribute.SkillSpeed] = statValue;
                    break;
                case 1407:
                    stats[(int)PlayerAttribute.SpellSpeed] = statValue;
                    break;
                case 1408:
                    stats[(int)PlayerAttribute.Tenacity] = statValue;
                    break;
                case 1409:
                    stats[(int)PlayerAttribute.Piety] = statValue;
                    break;
            }
        }

        return stats;
    }

    private void ApplyExtraStats(Dictionary<int, int> stats, Dictionary<int, int> extraStats)
    {
        foreach (var (attribute, value) in extraStats)
        {
            if (!stats.ContainsKey(attribute))
            {
                continue;
            }

            stats[attribute] += value;
        }
    }

    // ── Packet firewall detours (mirrored from Hyperborea Memory.cs) ──────────

    private byte SendPacketDetour(nint a1, nint a2, nint a3, byte a4)
    {
        const byte defaultReturn = 1;
        if (a2 == IntPtr.Zero) return defaultReturn;
        try
        {
            if (*(ushort*)a2 == heartbeatOpcode)
                return sendPacketHook.Original(a1, a2, a3, a4);
        }
        catch (Exception e)
        {
            Plugin.Log.Error($"[ZoneSession] SendPacketDetour: {e.Message}");
            return defaultReturn;
        }
        return defaultReturn;
    }

    private void ReceivePacketDetour(PacketDispatcher* a1, uint a2, nint a3)
    {
        if (a3 == IntPtr.Zero) return;
        try
        {
            // Release builds always run the firewall (safe mode hardcoded on).
            // Debug builds honour the config toggle so it can be flipped off
            // for testing without affecting shipped behaviour.
#if DEBUG
            var safeMode = Plugin.Config.SafeMode;
#else
            const bool safeMode = true;
#endif
            if (!safeMode || Plugin.Config.ZoneDownOpcodes.Contains(*(ushort*)(a3 + 2)))
                receivePacketHook.Original(a1, a2, a3);
        }
        catch (Exception e)
        {
            Plugin.Log.Error($"[ZoneSession] ReceivePacketDetour: {e.Message}");
        }
    }

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    public void Dispose()
    {
        Plugin.AddonLifecycle.UnregisterListener(AddonEvent.PostSetup, "Social", OnSocialPostSetup);

        // To not freeze a player that's disabling/reloading/etc the plugin while not in a Scenario
        if (IsActive)
        {
            Revert(true);
        }
        else
        {
            DisableFirewall(); // To be sure the Hooks are disabled before calling Dispose
        }

        sendPacketHook.Dispose();
        receivePacketHook.Dispose();
    }
}
