// Generated by tools/parser.py --code. Edit freely.
// Player id -> role mapping (first-seen order inside the window):
//   100A9810  -> PartyRole.MainTank
//   100B5ADE  -> PartyRole.OffTank
//   1004C6E4  -> PartyRole.RegenHealer
//   100D8948  -> PartyRole.ShieldHealer
//   10069112  -> PartyRole.MeleeDpsA
//   1001A114  -> PartyRole.MeleeDpsB
//   100192F0  -> PartyRole.PhysRangedDps
//   1004BD9C  -> PartyRole.CasterDps
// Suppressed 261|Change keys (state-sync churn — no C# emission):
//   CurrentMP, Heading, MaxHP, NPCTargetID, PosX, PosY, PosZ

using System.Collections.Generic;
using System.Numerics;
using AnoMech.Core.Game;
using AnoMech.Core.Game.Ai;
using AnoMech.Core.Game.Party;
using AnoMech.Core.Map;
using AnoMech.Core.SimObjects;

namespace AnoMech.Scenarios.Umad;

public sealed class UmadP5ForsakenNull : IScenario
{
    public string Name => "Forsaken Null";
    public IPhase Phase => UmadZone.P5;

    private SimWorld world = null!;
    private SimParty party = null!;

    public IReadOnlyList<IScenarioAi> AiStrats => [];

    public void Run(SimWorld worldParam, int? selectAi)
    {
        world = worldParam;
        party = worldParam.Party;

        Run_Kefka_4001DE6B();
        Run_Kefka_4001D7AD();
        Run_Kefka_4001D7AE();
        Run_Kefka_4001D7AF();
        Run_Kefka_4001D7AC();
        Run_Kefka_4001D7AB();
        Run_InstanceEvents();
        Run_PlayerLockons();
    }

    private void Run_InstanceEvents()
    {
        // [3.13s] 33|800375D2|80000027|28|02|1BDB|4001DE6B|81b98a9e11ebe369
        world.Events.Add(3.13f, () => world.Map.DirectorUpdate(0x80000027U, 0x28U, 0x2U, 0x1BDBU, 0x4001DE6BU));
        // [15.20s] 257|800375D2|00200010|1D|||14051e89b75ace01
        world.Events.Add(15.20f, () => world.Map.AddEffect(packetFlags: 0x00200010U, index: (byte)0x1D));
        // [18.85s] 257|800375D2|00200010|1C|||51c9f7d96335d692
        world.Events.Add(18.85f, () => world.Map.AddEffect(packetFlags: 0x00200010U, index: (byte)0x1C));
        // [18.85s] 257|800375D2|00200010|14|||d487524d344c544a
        world.Events.Add(18.85f, () => world.Map.AddEffect(packetFlags: 0x00200010U, index: (byte)0x14));
        // [21.30s] 33|800375D2|80000027|29|02|1BDB|4001DE6B|28d4b7f730510ce1
        world.Events.Add(21.30f, () => world.Map.DirectorUpdate(0x80000027U, 0x29U, 0x2U, 0x1BDBU, 0x4001DE6BU));
        // [23.40s] 257|800375D2|00200010|1E|||c13acb2fee546bff
        world.Events.Add(23.40f, () => world.Map.AddEffect(packetFlags: 0x00200010U, index: (byte)0x1E));
        // [27.05s] 257|800375D2|00200010|19|||d9ab9336679476bf
        world.Events.Add(27.05f, () => world.Map.AddEffect(packetFlags: 0x00200010U, index: (byte)0x19));
        // [27.05s] 257|800375D2|00200010|1A|||1d4bae009b12e7fe
        world.Events.Add(27.05f, () => world.Map.AddEffect(packetFlags: 0x00200010U, index: (byte)0x1A));
        // [29.46s] 33|800375D2|80000027|2A|02|1BDB|4001DE6B|484089def11a49ca
        world.Events.Add(29.46f, () => world.Map.DirectorUpdate(0x80000027U, 0x2AU, 0x2U, 0x1BDBU, 0x4001DE6BU));
        // [31.55s] 257|800375D2|00200010|1F|||26f185c5902905be
        world.Events.Add(31.55f, () => world.Map.AddEffect(packetFlags: 0x00200010U, index: (byte)0x1F));
        // [35.20s] 257|800375D2|00200010|16|||0d7e4e057f572640
        world.Events.Add(35.20f, () => world.Map.AddEffect(packetFlags: 0x00200010U, index: (byte)0x16));
        // [35.20s] 257|800375D2|00200010|1B|||eae254037e80b74e
        world.Events.Add(35.20f, () => world.Map.AddEffect(packetFlags: 0x00200010U, index: (byte)0x1B));
        // [37.61s] 33|800375D2|80000027|2B|02|1BDB|4001DE6B|81cbb1ea4bbb5da3
        world.Events.Add(37.61f, () => world.Map.DirectorUpdate(0x80000027U, 0x2BU, 0x2U, 0x1BDBU, 0x4001DE6BU));
        // [39.70s] 257|800375D2|00200010|20|||e52c8be7d1995ac8
        world.Events.Add(39.70f, () => world.Map.AddEffect(packetFlags: 0x00200010U, index: (byte)0x20));
        // [43.35s] 257|800375D2|00200010|18|||da77070d76149fcc
        world.Events.Add(43.35f, () => world.Map.AddEffect(packetFlags: 0x00200010U, index: (byte)0x18));
        // [43.35s] 257|800375D2|00200010|15|||2785591de490e0dc
        world.Events.Add(43.35f, () => world.Map.AddEffect(packetFlags: 0x00200010U, index: (byte)0x15));
        // [48.61s] 257|800375D2|00100008|21|||cea826c6d617f8e8
        world.Events.Add(48.61f, () => world.Map.AddEffect(packetFlags: 0x00100008U, index: (byte)0x21));
        // [48.61s] 257|800375D2|00080004|1E|||f0fd26c05cd001d0
        world.Events.Add(48.61f, () => world.Map.AddEffect(packetFlags: 0x00080004U, index: (byte)0x1E));
        // [48.61s] 257|800375D2|00080004|1F|||25991d4253698112
        world.Events.Add(48.61f, () => world.Map.AddEffect(packetFlags: 0x00080004U, index: (byte)0x1F));
        // [48.61s] 257|800375D2|00080004|1D|||fe2d56dc9e0f1061
        world.Events.Add(48.61f, () => world.Map.AddEffect(packetFlags: 0x00080004U, index: (byte)0x1D));
        // [48.61s] 257|800375D2|00080004|20|||2add94f66a25aa2e
        world.Events.Add(48.61f, () => world.Map.AddEffect(packetFlags: 0x00080004U, index: (byte)0x20));
        // [52.13s] 33|800375D2|80000027|2C|02|1BDB|4001DE6B|776d1541c7b6c741
        world.Events.Add(52.13f, () => world.Map.DirectorUpdate(0x80000027U, 0x2CU, 0x2U, 0x1BDBU, 0x4001DE6BU));
    }

    private void Run_PlayerLockons()
    {
        // [13.20s] 27|100B5ADE|OffTank|0000|0000|00A1|100B5ADE|0000|0000|6595320e0a22af6f
        world.Events.Add(13.20f, () => party.Player?.AttachLockonVfx(Constants.LockonId.X_A1, persistent: false));
        // [21.39s] 27|100B5ADE|OffTank|0000|0000|00A1|100B5ADE|0000|0000|6a884bdf06095027
        world.Events.Add(21.39f, () => party.Player?.AttachLockonVfx(Constants.LockonId.X_A1, persistent: false));
        // [29.55s] 27|100D8948|ShieldHealer|0000|0000|00A1|100D8948|0000|0000|dd4334bf3008bacd
        world.Events.Add(29.55f, () => party.Player?.AttachLockonVfx(Constants.LockonId.X_A1, persistent: false));
        // [37.69s] 27|1004C6E4|RegenHealer|0000|0000|00A1|1004C6E4|0000|0000|d2dbe49a3929e409
        world.Events.Add(37.69f, () => party.Player?.AttachLockonVfx(Constants.LockonId.X_A1, persistent: false));
    }

    public void Tick(float delta, float elapsed) { }

    private void Run_Kefka_4001DE6B()
    {
        SimEnemy? kefka_4001DE6B = null;
        world.Events.Add(0f, () => kefka_4001DE6B = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: Constants.BNpcBaseId.Kefka, NameId: Constants.BNpcNameId.Kefka, Level: 100, Targetable: true, EnemyList: EnemyListMode.Always, IsVisible: true, Placement: new Placement(new Vector3(0.000f, 0.000f, 0.000f), 0.000f))));
        
        world.Events.Add(1.08f, () => kefka_4001DE6B?.Cast(Constants.ActionId.UnknownC652, castSeconds: 0f, targetId: kefka_4001DE6B?.GameObjectId));
        world.Events.Add(3.21f, () => kefka_4001DE6B?.Cast(Constants.ActionId.Forsaken));
        world.Events.Add(13.20f, () => kefka_4001DE6B?.AddStatus(Constants.StatusId.DirectionalDisregard));
        world.Events.Add(21.39f, () => kefka_4001DE6B?.Cast(Constants.ActionId.Forsaken_BB36));
        world.Events.Add(29.55f, () => kefka_4001DE6B?.Cast(Constants.ActionId.Forsaken_BB36));
        world.Events.Add(37.69f, () => kefka_4001DE6B?.Cast(Constants.ActionId.Forsaken_BB36));
    }

    private void Run_Kefka_4001D7AD()
    {
        SimEnemy? kefka_4001D7AD = null;
        world.Events.Add(0f, () => kefka_4001D7AD = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: Constants.BNpcBaseId.Kefka_233C, NameId: Constants.BNpcNameId.Kefka, Level: 1, Targetable: false, EnemyList: EnemyListMode.Never, IsVisible: false, Placement: new Placement(new Vector3(0.000f, 0.000f, 0.000f), -3.110f))));
        world.Events.Add(13.20f, () => kefka_4001D7AD?.SetPosition(new Placement(new Vector3(0.000f, 0.000f, 13.500f), 0.000f)));
        world.Events.Add(13.28f, () => kefka_4001D7AD?.Cast(Constants.ActionId.Forsaken_BB38));
        world.Events.Add(21.39f, () => kefka_4001D7AD?.SetPosition(new Placement(new Vector3(-7.000f, 0.000f, 6.750f), 0.000f)));
        world.Events.Add(21.48f, () => kefka_4001D7AD?.Cast(Constants.ActionId.Forsaken_BB38));
        world.Events.Add(29.55f, () => kefka_4001D7AD?.SetPosition(new Placement(new Vector3(-6.750f, 0.000f, -6.750f), 0.000f)));
        world.Events.Add(29.63f, () => kefka_4001D7AD?.Cast(Constants.ActionId.Forsaken_BB38));
        world.Events.Add(37.69f, () => kefka_4001D7AD?.SetPosition(new Placement(new Vector3(7.000f, 0.000f, -6.750f), 0.000f)));
        world.Events.Add(37.78f, () => kefka_4001D7AD?.Cast(Constants.ActionId.Forsaken_BB38));
    }

    private void Run_Kefka_4001D7AE()
    {
        SimEnemy? kefka_4001D7AE = null;
        world.Events.Add(0f, () => kefka_4001D7AE = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: Constants.BNpcBaseId.Kefka_233C, NameId: Constants.BNpcNameId.Kefka, Level: 1, Targetable: false, EnemyList: EnemyListMode.Never, IsVisible: false, Placement: new Placement(new Vector3(0.000f, 0.000f, 0.000f), -3.110f))));
        world.Events.Add(13.20f, () => kefka_4001D7AE?.SetPosition(new Placement(new Vector3(-13.500f, 0.000f, 13.500f), 0.000f)));
        world.Events.Add(13.28f, () => kefka_4001D7AE?.Cast(Constants.ActionId.ForsakenGround));
        world.Events.Add(21.39f, () => kefka_4001D7AE?.SetPosition(new Placement(new Vector3(13.500f, 0.000f, 13.500f), 0.000f)));
        world.Events.Add(21.48f, () => kefka_4001D7AE?.Cast(Constants.ActionId.ForsakenGround));
        world.Events.Add(29.55f, () => kefka_4001D7AE?.SetPosition(new Placement(new Vector3(0.000f, 0.000f, -13.500f), 0.000f)));
        world.Events.Add(29.63f, () => kefka_4001D7AE?.Cast(Constants.ActionId.ForsakenGround));
        world.Events.Add(37.69f, () => kefka_4001D7AE?.SetPosition(new Placement(new Vector3(0.000f, 0.000f, 13.500f), 0.000f)));
        world.Events.Add(37.78f, () => kefka_4001D7AE?.Cast(Constants.ActionId.ForsakenGround));
    }

    private void Run_Kefka_4001D7AF()
    {
        SimEnemy? kefka_4001D7AF = null;
        world.Events.Add(0f, () => kefka_4001D7AF = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: Constants.BNpcBaseId.Kefka_233C, NameId: Constants.BNpcNameId.Kefka, Level: 1, Targetable: false, EnemyList: EnemyListMode.Never, IsVisible: false, Placement: new Placement(new Vector3(0.000f, 0.000f, 0.000f), -3.110f))));
        world.Events.Add(13.20f, () => kefka_4001D7AF?.SetPosition(new Placement(new Vector3(0.000f, 0.000f, 0.000f), 0.000f)));
        world.Events.Add(13.28f, () => kefka_4001D7AF?.Cast(Constants.ActionId.ForsakenGround));
        world.Events.Add(21.39f, () => kefka_4001D7AF?.SetPosition(new Placement(new Vector3(13.500f, 0.000f, -13.500f), 0.000f)));
        world.Events.Add(21.48f, () => kefka_4001D7AF?.Cast(Constants.ActionId.ForsakenGround));
        world.Events.Add(29.55f, () => kefka_4001D7AF?.SetPosition(new Placement(new Vector3(-13.500f, 0.000f, -13.500f), 0.000f)));
        world.Events.Add(29.63f, () => kefka_4001D7AF?.Cast(Constants.ActionId.ForsakenGround));
        world.Events.Add(37.69f, () => kefka_4001D7AF?.SetPosition(new Placement(new Vector3(13.500f, 0.000f, 0.000f), 0.000f)));
        world.Events.Add(37.78f, () => kefka_4001D7AF?.Cast(Constants.ActionId.ForsakenGround));
    }

    private void Run_Kefka_4001D7AC()
    {
        SimEnemy? kefka_4001D7AC = null;
        world.Events.Add(0f, () => kefka_4001D7AC = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: Constants.BNpcBaseId.Kefka_233C, NameId: Constants.BNpcNameId.Kefka, Level: 1, Targetable: false, EnemyList: EnemyListMode.Never, IsVisible: false, Placement: new Placement(new Vector3(0.000f, 0.000f, 0.000f), -3.110f))));
        world.Events.Add(18.32f, () => kefka_4001D7AC?.Cast(Constants.ActionId.ForsakenBonds, castSeconds: 0f, targetId: party.Player?.GameObjectId));
        world.Events.Add(26.47f, () => kefka_4001D7AC?.Cast(Constants.ActionId.ForsakenBonds, castSeconds: 0f, targetId: party.Player?.GameObjectId));
        world.Events.Add(34.62f, () => kefka_4001D7AC?.Cast(Constants.ActionId.ForsakenBonds, castSeconds: 0f, targetId: party.Player?.GameObjectId));
        world.Events.Add(42.78f, () => kefka_4001D7AC?.Cast(Constants.ActionId.ForsakenBonds, castSeconds: 0f, targetId: party.Player?.GameObjectId));
    }

    private void Run_Kefka_4001D7AB()
    {
        SimEnemy? kefka_4001D7AB = null;
        world.Events.Add(0f, () => kefka_4001D7AB = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: Constants.BNpcBaseId.Kefka_233C, NameId: Constants.BNpcNameId.Kefka, Level: 1, Targetable: false, EnemyList: EnemyListMode.Never, IsVisible: false, Placement: new Placement(new Vector3(10.610f, 0.000f, -10.610f), 0.790f))));
        // world.Events.Add(41.88f, () => kefka_4001D7AB?.Cast(Constants.ActionId.UnknownC61a, castSeconds: 0f, targetId: party.Get(PartyRole.RegenHealer)?.GameObjectId));
        // world.Events.Add(42.06f, () => party.Get(PartyRole.RegenHealer)?.AddStatus(Constants.StatusId.Forsaken));
    }

    public static class Constants
    {
        public static class BNpcBaseId
        {
            public const uint Kefka = 19511;
            public const uint Kefka_233C = 9020;
        }

        public static class BNpcNameId
        {
            public const uint Kefka = 7131;
        }

        public static class ActionId
        {
            public const uint BlizzardIII = 0xBB44U;
            public const uint CatastrophicChoice = 0xC24EU;
            public const uint CatastrophicChoice_C24F = 0xC24FU;
            public const uint Celestriad = 0xBB42U;
            public const uint ChaoticFlare = 0xBB53U;
            public const uint ChaoticFlood = 0xBB4FU;
            public const uint ChaoticHoly = 0xBB56U;
            public const uint FellForces = 0xC654U;
            public const uint FellForces_C653 = 0xC653U;
            public const uint FellForces_C655 = 0xC655U;
            public const uint FireIII = 0xBB43U;
            public const uint Flare = 0xBB52U;
            public const uint FlareDiffusion = 0xBB55U;
            public const uint Flood = 0xC13FU;
            public const uint Flood_C269 = 0xC269U;
            public const uint Forsaken = 0xBB35U;
            public const uint ForsakenBonds = 0xBB39U;
            public const uint ForsakenGround = 0xBB37U;
            public const uint ForsakenNull = 0xBB3AU;
            public const uint Forsaken_BB36 = 0xBB36U;
            public const uint Forsaken_BB38 = 0xBB38U;
            public const uint Holy = 0xBB54U;
            public const uint MaddeningOrchestra = 0xBB50U;
            public const uint MaddeningOrchestra_BB51 = 0xBB51U;
            public const uint StrayApocalypse = 0xBB3BU;
            public const uint StrayApocalypse_BB3C = 0xBB3CU;
            public const uint StrayApocalypse_BB3D = 0xBB3DU;
            public const uint StrayEntropy = 0xBB3EU;
            public const uint StrayEntropy_BB3F = 0xBB3FU;
            public const uint ThunderIII = 0xBB45U;
            public const uint Tornado = 0xBB4BU;
            public const uint UltimaRepeater = 0xBB40U;
            public const uint UltimaRepeater_BB41 = 0xBB41U;
            public const uint UnknownC183 = 0xC183U;
            public const uint UnknownC61a = 0xC61AU;
            public const uint UnknownC652 = 0xC652U;
        }

        public static class StatusId
        {
            public const ushort DamageDown = (ushort)0xB5F;
            public const ushort DirectionalDisregard = (ushort)0xEE0;
            public const ushort FireResistanceDownII = (ushort)0xB56;
            public const ushort Forsaken = (ushort)0x1418;
            public const ushort IceResistanceDownII = (ushort)0xB57;
            public const ushort LightningResistanceDownII = (ushort)0xBB6;
            public const ushort MagicVulnerabilityUp = (ushort)0xB7D;
            public const ushort Transcendent = (ushort)0x1A2;
        }

        public static class LockonId
        {
            public const uint X_A1 = 161;
        }
    }
}
