// <auto-generated>
//   Produced by tools/replay_export_rsv_rsf.py
//   Source replay(s): Dancing Mad (Ultimate) 2026.07.09 18.52.30.dat
//   Game build(s): 13592030
//   RSV: 386 rows (350 text, 36 raw)  |  RSF: 220 records
//   Re-run the extractor against a newer replay to refresh; do not edit by hand.
// </auto-generated>
using System;
using AnoMech.Core.Native;

namespace AnoMech.Scenarios.Umad;

// RSV (text) + RSF (file paths) captured from a duty replay. Scenarios run inn-only
// so the server never delivers these; Seed() writes them into the game's native
// tables at scenario start. See replay_export_rsv_rsf.py and memory
// reference_rsv_action_names.
public static class UmadReplayData
{
    // Verbatim RSV key -> resolved UTF-8 text (action / status names, boss dialogue).
    private static readonly (string Key, string Value)[] RsvText =
    [
        ("_rsv_4887_-1_1_0_0_S74CFC3B0_E74CFC3B0", "White Wound"),
        ("_rsv_4887_-1_1_0_1_S74CFC3B0_E74CFC3B0", "White Wound"),
        ("_rsv_4888_-1_1_0_0_S74CFC3B0_E74CFC3B0", "Black Wound"),
        ("_rsv_4888_-1_1_0_1_S74CFC3B0_E74CFC3B0", "Black Wound"),
        ("_rsv_5078_-1_1_0_0_S74CFC3B0_E74CFC3B0", "Double-trouble Trap"),
        ("_rsv_5078_-1_1_0_1_S74CFC3B0_E74CFC3B0", "Double-trouble Trap"),
        ("_rsv_5083_-1_1_0_0_S74CFC3B0_E74CFC3B0", "Spells' Trouble"),
        ("_rsv_5083_-1_1_0_1_S74CFC3B0_E74CFC3B0", "Spells' Trouble"),
        ("_rsv_5083_-1_1_1_0_S74CFC3B0_E74CFC3B0", "Burdened by a number of magicks. A spell will activate when hit by a wave of Kefka's own magicks, decreasing stacks. Damage taken from Light of Judgment is greatly increased while under this effect."),
        ("_rsv_5083_-1_1_1_1_S74CFC3B0_E74CFC3B0", "Burdened by a number of magicks. A spell will activate when hit by a wave of Kefka's own magicks, decreasing stacks. Damage taken from Light of Judgment is greatly increased while under this effect."),
        ("_rsv_5144_-1_1_0_0_S74CFC3B0_E74CFC3B0", "Forsaken"),
        ("_rsv_5144_-1_1_0_1_S74CFC3B0_E74CFC3B0", "Forsaken"),
        ("_rsv_5144_-1_1_1_0_S74CFC3B0_E74CFC3B0", "Vanished, sense of self having been eroded by destructive power."),
        ("_rsv_5144_-1_1_1_1_S74CFC3B0_E74CFC3B0", "Vanished, sense of self having been eroded by destructive power."),
        ("_rsv_5350_-1_1_0_0_S74CFC3B0_E74CFC3B0", "Surprise Flare"),
        ("_rsv_5350_-1_1_0_1_S74CFC3B0_E74CFC3B0", "Surprise Flare"),
        ("_rsv_5351_-1_1_0_0_S74CFC3B0_E74CFC3B0", "Surprise Holy"),
        ("_rsv_5351_-1_1_0_1_S74CFC3B0_E74CFC3B0", "Surprise Holy"),
        ("_rsv_5452_-1_1_0_0_S74CFC3B0_E74CFC3B0", "Unbecoming"),
        ("_rsv_5452_-1_1_0_1_S74CFC3B0_E74CFC3B0", "Unbecoming"),
        ("_rsv_5452_-1_1_1_0_S74CFC3B0_E74CFC3B0", "In the process of being unmade. Accruing two stacks will reduce you to Meanest Existence."),
        ("_rsv_5452_-1_1_1_1_S74CFC3B0_E74CFC3B0", "In the process of being unmade. Accruing two stacks will reduce you to Meanest Existence."),
        ("_rsv_5453_-1_1_0_0_S74CFC3B0_E74CFC3B0", "Meanest Existence"),
        ("_rsv_5453_-1_1_0_1_S74CFC3B0_E74CFC3B0", "Meanest Existence"),
        ("_rsv_5454_-1_1_0_0_S74CFC3B0_E74CFC3B0", "Primordial Crust"),
        ("_rsv_5454_-1_1_0_1_S74CFC3B0_E74CFC3B0", "Primordial Crust"),
        ("_rsv_5454_-1_1_1_0_S74CFC3B0_E74CFC3B0", "Plagued by rapidly hardening mud. Effect dissipates when damage that would cause HP to drop below 0 is taken, leaving HP at 1."),
        ("_rsv_5454_-1_1_1_1_S74CFC3B0_E74CFC3B0", "Plagued by rapidly hardening mud. Effect dissipates when damage that would cause HP to drop below 0 is taken, leaving HP at 1."),
        ("_rsv_5464_-1_1_0_0_S74CFC3B0_E74CFC3B0", "Beyond Death"),
        ("_rsv_5464_-1_1_0_1_S74CFC3B0_E74CFC3B0", "Beyond Death"),
        ("_rsv_5464_-1_1_1_0_S74CFC3B0_E74CFC3B0", "Only beyond death's boundaries can life be achieved."),
        ("_rsv_5464_-1_1_1_1_S74CFC3B0_E74CFC3B0", "Only beyond death's boundaries can life be achieved."),
        ("_rsv_19494_-1_1_0_0_SCFE39641_ECFE39641", "Haha!"),
        ("_rsv_19494_-1_1_0_1_SCFE39641_ECFE39641", "Haha!"),
        ("_rsv_19495_-1_1_0_0_SCFE39641_ECFE39641", "There's no escape!"),
        ("_rsv_19495_-1_1_0_1_SCFE39641_ECFE39641", "There's no escape!"),
        ("_rsv_19496_-1_1_0_0_SCFE39641_ECFE39641", "That all you got?"),
        ("_rsv_19496_-1_1_0_1_SCFE39641_ECFE39641", "That all you got?"),
        ("_rsv_19497_-1_1_0_0_SCFE39641_ECFE39641", "Let's destroy everything!"),
        ("_rsv_19497_-1_1_0_1_SCFE39641_ECFE39641", "Let's destroy everything!"),
        ("_rsv_45504_-1_1_0_0_S13095D61_E13095D61", "Gahahahahaha! UNLEASH IT ALL!"),
        ("_rsv_45504_-1_1_0_1_S13095D61_E13095D61", "Gahahahahaha! UNLEASH IT ALL!"),
        ("_rsv_45505_-1_1_0_0_S13095D61_E13095D61", "Yes... I am filled with glorious purpose!"),
        ("_rsv_45505_-1_1_0_1_S13095D61_E13095D61", "Yes... I am filled with glorious purpose!"),
        ("_rsv_45507_-1_1_0_0_S13095D61_E13095D61", "Such things as those...are mine to destroy!"),
        ("_rsv_45507_-1_1_0_1_S13095D61_E13095D61", "Such things as those...are mine to destroy!"),
        ("_rsv_45508_-1_1_0_0_S13095D61_E13095D61", "I'm afraid that's all I have time for today. Bye-bye now!"),
        ("_rsv_45508_-1_1_0_1_S13095D61_E13095D61", "I'm afraid that's all I have time for today. Bye-bye now!"),
        ("_rsv_45509_-1_1_0_0_S13095D61_E13095D61", "Destroy! Destroy! Destroy! ...I will destroy it all!!!"),
        ("_rsv_45509_-1_1_0_1_S13095D61_E13095D61", "Destroy! Destroy! Destroy! ...I will destroy it all!!!"),
        ("_rsv_45511_-1_1_0_0_S13095D61_E13095D61", "What!? There's no way that didn't work!"),
        ("_rsv_45511_-1_1_0_1_S13095D61_E13095D61", "What!? There's no way that didn't work!"),
        ("_rsv_45512_-1_1_0_0_S13095D61_E13095D61", "How boring. Guess I'll have to spice things up!"),
        ("_rsv_45512_-1_1_0_1_S13095D61_E13095D61", "How boring. Guess I'll have to spice things up!"),
        ("_rsv_45513_-1_1_0_0_S13095D61_E13095D61", "Intriguing. This clearly isn't your first time..."),
        ("_rsv_45513_-1_1_0_1_S13095D61_E13095D61", "Intriguing. This clearly isn't your first time..."),
        ("_rsv_45515_-1_1_0_0_S13095D61_E13095D61", "Crafty little bastards, aren't you?"),
        ("_rsv_45515_-1_1_0_1_S13095D61_E13095D61", "Crafty little bastards, aren't you?"),
        ("_rsv_45516_-1_1_0_0_S13095D61_E13095D61", "Hmph. I see what's going on here."),
        ("_rsv_45516_-1_1_0_1_S13095D61_E13095D61", "Hmph. I see what's going on here."),
        ("_rsv_45517_-1_1_0_0_S13095D61_E13095D61", "Oh, you're in for it now!"),
        ("_rsv_45517_-1_1_0_1_S13095D61_E13095D61", "Oh, you're in for it now!"),
        ("_rsv_45518_-1_1_0_0_S13095D61_E13095D61", "Who am I talking to?"),
        ("_rsv_45518_-1_1_0_1_S13095D61_E13095D61", "Who am I talking to?"),
        ("_rsv_45520_-1_1_0_0_S13095D61_E13095D61", "Right! Let's see if I can't take the reins for a spell..."),
        ("_rsv_45520_-1_1_0_1_S13095D61_E13095D61", "Right! Let's see if I can't take the reins for a spell..."),
        ("_rsv_45521_-1_1_0_0_S13095D61_E13095D61", "Hahaha! There's nothing I can't do!"),
        ("_rsv_45521_-1_1_0_1_S13095D61_E13095D61", "Hahaha! There's nothing I can't do!"),
        ("_rsv_45522_-1_1_0_0_S13095D61_E13095D61", "Oh! What other toys can I throw in here..."),
        ("_rsv_45522_-1_1_0_1_S13095D61_E13095D61", "Oh! What other toys can I throw in here..."),
        ("_rsv_45523_-1_1_0_0_S13095D61_E13095D61", "Ohohohoho! What a marvelous sensation!"),
        ("_rsv_45523_-1_1_0_1_S13095D61_E13095D61", "Ohohohoho! What a marvelous sensation!"),
        ("_rsv_45524_-1_1_0_0_S13095D61_E13095D61", "Jealous? Enthralled? I don't blame you!"),
        ("_rsv_45524_-1_1_0_1_S13095D61_E13095D61", "Jealous? Enthralled? I don't blame you!"),
        ("_rsv_45525_-1_1_0_0_S13095D61_E13095D61", "Careful now!"),
        ("_rsv_45525_-1_1_0_1_S13095D61_E13095D61", "Careful now!"),
        ("_rsv_45526_-1_1_0_0_S13095D61_E13095D61", "I've got big ambitions and a big attitude..."),
        ("_rsv_45526_-1_1_0_1_S13095D61_E13095D61", "I've got big ambitions and a big attitude..."),
        ("_rsv_45527_-1_1_0_0_S13095D61_E13095D61", "And now a big body to match\u2500behold!"),
        ("_rsv_45527_-1_1_0_1_S13095D61_E13095D61", "And now a big body to match\u2500behold!"),
        ("_rsv_45528_-1_1_0_0_S13095D61_E13095D61", "Take this! And that! And one of these!"),
        ("_rsv_45528_-1_1_0_1_S13095D61_E13095D61", "Take this! And that! And one of these!"),
        ("_rsv_45529_-1_1_0_0_S13095D61_E13095D61", "Aaand... Kaboom!"),
        ("_rsv_45529_-1_1_0_1_S13095D61_E13095D61", "Aaand... Kaboom!"),
        ("_rsv_45530_-1_1_0_0_S13095D61_E13095D61", "Dance! Dance for me!"),
        ("_rsv_45530_-1_1_0_1_S13095D61_E13095D61", "Dance! Dance for me!"),
        ("_rsv_45531_-1_1_0_0_S13095D61_E13095D61", "Hey, look\u2500my friends are back!"),
        ("_rsv_45531_-1_1_0_1_S13095D61_E13095D61", "Hey, look\u2500my friends are back!"),
        ("_rsv_45532_-1_1_0_0_S13095D61_E13095D61", "Go on then, make yourselves useful!"),
        ("_rsv_45532_-1_1_0_1_S13095D61_E13095D61", "Go on then, make yourselves useful!"),
        ("_rsv_45533_-1_1_0_0_S13095D61_E13095D61", "Oh, you were so close! But close isn't good enough!"),
        ("_rsv_45533_-1_1_0_1_S13095D61_E13095D61", "Oh, you were so close! But close isn't good enough!"),
        ("_rsv_45534_-1_1_0_0_S13095D61_E13095D61", "Destruction is the fate of all things."),
        ("_rsv_45534_-1_1_0_1_S13095D61_E13095D61", "Destruction is the fate of all things."),
        ("_rsv_45535_-1_1_0_0_S13095D61_E13095D61", "Anything you fools would dare build..."),
        ("_rsv_45535_-1_1_0_1_S13095D61_E13095D61", "Anything you fools would dare build..."),
        ("_rsv_45536_-1_1_0_0_S13095D61_E13095D61", "I'll raze to the ground with a smile!"),
        ("_rsv_45536_-1_1_0_1_S13095D61_E13095D61", "I'll raze to the ground with a smile!"),
        ("_rsv_45537_-1_1_0_0_S13095D61_E13095D61", "Embrace oblivion!"),
        ("_rsv_45537_-1_1_0_1_S13095D61_E13095D61", "Embrace oblivion!"),
        ("_rsv_45538_-1_1_0_0_S13095D61_E13095D61", "Let the party begin!"),
        ("_rsv_45538_-1_1_0_1_S13095D61_E13095D61", "Let the party begin!"),
        ("_rsv_45539_-1_1_0_0_S13095D61_E13095D61", "Sizzle, crackle, and zap!"),
        ("_rsv_45539_-1_1_0_1_S13095D61_E13095D61", "Sizzle, crackle, and zap!"),
        ("_rsv_45540_-1_1_0_0_S13095D61_E13095D61", "Ugh! You lot are no fun at all!"),
        ("_rsv_45540_-1_1_0_1_S13095D61_E13095D61", "Ugh! You lot are no fun at all!"),
        ("_rsv_45543_-1_1_0_0_S13095D61_E13095D61", "You, your friends, this wretched world\u2500I'll destroy everything!"),
        ("_rsv_45543_-1_1_0_1_S13095D61_E13095D61", "You, your friends, this wretched world\u2500I'll destroy everything!"),
        ("_rsv_45545_-1_1_0_0_S13095D61_E13095D61", "Better luck next time, kids!"),
        ("_rsv_45545_-1_1_0_1_S13095D61_E13095D61", "Better luck next time, kids!"),
        ("_rsv_45546_-1_1_0_0_S13095D61_E13095D61", "Boring!"),
        ("_rsv_45546_-1_1_0_1_S13095D61_E13095D61", "Boring!"),
        ("_rsv_45547_-1_1_0_0_S13095D61_E13095D61", "Here I go!"),
        ("_rsv_45547_-1_1_0_1_S13095D61_E13095D61", "Here I go!"),
        ("_rsv_47842_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Definition of Insanity"),
        ("_rsv_47842_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Definition of Insanity"),
        ("_rsv_47843_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Ultima Blaster"),
        ("_rsv_47843_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Ultima Blaster"),
        ("_rsv_47844_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Ultima Blaster"),
        ("_rsv_47844_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Ultima Blaster"),
        ("_rsv_47845_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Max"),
        ("_rsv_47845_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Max"),
        ("_rsv_47846_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Slap Happy"),
        ("_rsv_47846_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Slap Happy"),
        ("_rsv_47847_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Slap Happy"),
        ("_rsv_47847_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Slap Happy"),
        ("_rsv_47848_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Slap Happy"),
        ("_rsv_47848_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Slap Happy"),
        ("_rsv_47849_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Slap Happy"),
        ("_rsv_47849_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Slap Happy"),
        ("_rsv_47850_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Shocking Impact"),
        ("_rsv_47850_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Shocking Impact"),
        ("_rsv_47851_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Shockwave"),
        ("_rsv_47851_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Shockwave"),
        ("_rsv_47852_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Look upon Me and Despair"),
        ("_rsv_47852_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Look upon Me and Despair"),
        ("_rsv_47853_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Look upon Me and Despair"),
        ("_rsv_47853_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Look upon Me and Despair"),
        ("_rsv_47854_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Look upon Me and Despair"),
        ("_rsv_47854_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Look upon Me and Despair"),
        ("_rsv_47855_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stomp-a-Mole"),
        ("_rsv_47855_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stomp-a-Mole"),
        ("_rsv_47856_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stomp-a-Mole"),
        ("_rsv_47856_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stomp-a-Mole"),
        ("_rsv_47857_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Unmitigated Impact"),
        ("_rsv_47857_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Unmitigated Impact"),
        ("_rsv_47858_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Bowels of Agony"),
        ("_rsv_47858_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Bowels of Agony"),
        ("_rsv_47859_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stray Flames"),
        ("_rsv_47859_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stray Flames"),
        ("_rsv_47860_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Inferno"),
        ("_rsv_47860_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Inferno"),
        ("_rsv_47861_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Tsunami"),
        ("_rsv_47861_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Tsunami"),
        ("_rsv_47862_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stray Spray"),
        ("_rsv_47862_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stray Spray"),
        ("_rsv_47863_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stray Gusts"),
        ("_rsv_47863_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stray Gusts"),
        ("_rsv_47864_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Cyclone"),
        ("_rsv_47864_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Cyclone"),
        ("_rsv_47865_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stray Earth"),
        ("_rsv_47865_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stray Earth"),
        ("_rsv_47866_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Earthquake"),
        ("_rsv_47866_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Earthquake"),
        ("_rsv_47867_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Black Hole"),
        ("_rsv_47867_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Black Hole"),
        ("_rsv_47868_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Nothingness"),
        ("_rsv_47868_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Nothingness"),
        ("_rsv_47869_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Longitudinal Implosion"),
        ("_rsv_47869_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Longitudinal Implosion"),
        ("_rsv_47870_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Latitudinal Implosion"),
        ("_rsv_47870_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Latitudinal Implosion"),
        ("_rsv_47871_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Shockwave"),
        ("_rsv_47871_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Shockwave"),
        ("_rsv_47872_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Umbra Smash"),
        ("_rsv_47872_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Umbra Smash"),
        ("_rsv_47873_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Damning Edict"),
        ("_rsv_47873_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Damning Edict"),
        ("_rsv_47874_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Knock Down"),
        ("_rsv_47874_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Knock Down"),
        ("_rsv_47875_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Knock Down"),
        ("_rsv_47875_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Knock Down"),
        ("_rsv_47877_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Big Bang"),
        ("_rsv_47877_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Big Bang"),
        ("_rsv_47878_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Big Bang"),
        ("_rsv_47878_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Big Bang"),
        ("_rsv_47881_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Thunder III"),
        ("_rsv_47881_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Thunder III"),
        ("_rsv_47883_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Fire III"),
        ("_rsv_47883_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Fire III"),
        ("_rsv_47884_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Thunder III"),
        ("_rsv_47884_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Thunder III"),
        ("_rsv_47885_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Blizzard III"),
        ("_rsv_47885_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Blizzard III"),
        ("_rsv_47886_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Fire III"),
        ("_rsv_47886_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Fire III"),
        ("_rsv_47887_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Blizzard III"),
        ("_rsv_47887_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Blizzard III"),
        ("_rsv_47888_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Fire III"),
        ("_rsv_47888_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Fire III"),
        ("_rsv_47889_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Blizzard III"),
        ("_rsv_47889_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Blizzard III"),
        ("_rsv_47890_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Thunder III"),
        ("_rsv_47890_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Thunder III"),
        ("_rsv_47891_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Vacuum Wave"),
        ("_rsv_47891_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Vacuum Wave"),
        ("_rsv_47892_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Grand Cross"),
        ("_rsv_47892_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Grand Cross"),
        ("_rsv_47893_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Death Bomb"),
        ("_rsv_47893_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Death Bomb"),
        ("_rsv_47894_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Death Shriek"),
        ("_rsv_47894_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Death Shriek"),
        ("_rsv_47895_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Death Shriek"),
        ("_rsv_47895_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Death Shriek"),
        ("_rsv_47896_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Death Bolt"),
        ("_rsv_47896_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Death Bolt"),
        ("_rsv_47897_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Death Bolt"),
        ("_rsv_47897_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Death Bolt"),
        ("_rsv_47898_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Death Wave"),
        ("_rsv_47898_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Death Wave"),
        ("_rsv_47899_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Death Wave"),
        ("_rsv_47899_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Death Wave"),
        ("_rsv_47900_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Death Surge"),
        ("_rsv_47900_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Death Surge"),
        ("_rsv_47901_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Death Surge"),
        ("_rsv_47901_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Death Surge"),
        ("_rsv_47902_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Inferno"),
        ("_rsv_47902_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Inferno"),
        ("_rsv_47903_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Tsunami"),
        ("_rsv_47903_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Tsunami"),
        ("_rsv_47904_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Inferno"),
        ("_rsv_47904_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Inferno"),
        ("_rsv_47905_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Tsunami"),
        ("_rsv_47905_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Tsunami"),
        ("_rsv_47906_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stray Flames"),
        ("_rsv_47906_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stray Flames"),
        ("_rsv_47907_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stray Flames"),
        ("_rsv_47907_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stray Flames"),
        ("_rsv_47908_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stray Spray"),
        ("_rsv_47908_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stray Spray"),
        ("_rsv_47909_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stray Spray"),
        ("_rsv_47909_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stray Spray"),
        ("_rsv_47925_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Forsaken"),
        ("_rsv_47925_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Forsaken"),
        ("_rsv_47926_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Forsaken"),
        ("_rsv_47926_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Forsaken"),
        ("_rsv_47927_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Forsaken Ground"),
        ("_rsv_47927_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Forsaken Ground"),
        ("_rsv_47928_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Forsaken"),
        ("_rsv_47928_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Forsaken"),
        ("_rsv_47929_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Forsaken Bonds"),
        ("_rsv_47929_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Forsaken Bonds"),
        ("_rsv_47930_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Forsaken Null"),
        ("_rsv_47930_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Forsaken Null"),
        ("_rsv_47931_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stray Apocalypse"),
        ("_rsv_47931_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stray Apocalypse"),
        ("_rsv_47932_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stray Apocalypse"),
        ("_rsv_47932_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stray Apocalypse"),
        ("_rsv_47933_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stray Apocalypse"),
        ("_rsv_47933_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stray Apocalypse"),
        ("_rsv_47934_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stray Entropy"),
        ("_rsv_47934_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stray Entropy"),
        ("_rsv_47935_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stray Entropy"),
        ("_rsv_47935_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stray Entropy"),
        ("_rsv_47936_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Ultima Repeater"),
        ("_rsv_47936_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Ultima Repeater"),
        ("_rsv_47937_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Ultima Repeater"),
        ("_rsv_47937_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Ultima Repeater"),
        ("_rsv_47938_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Celestriad"),
        ("_rsv_47938_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Celestriad"),
        ("_rsv_47939_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Fire III"),
        ("_rsv_47939_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Fire III"),
        ("_rsv_47940_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Blizzard III"),
        ("_rsv_47940_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Blizzard III"),
        ("_rsv_47941_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Thunder III"),
        ("_rsv_47941_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Thunder III"),
        ("_rsv_47942_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stardust Fire III"),
        ("_rsv_47942_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stardust Fire III"),
        ("_rsv_47943_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stardust Blizzard III"),
        ("_rsv_47943_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stardust Blizzard III"),
        ("_rsv_47944_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Stardust Thunder III"),
        ("_rsv_47944_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Stardust Thunder III"),
        ("_rsv_47946_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Quake"),
        ("_rsv_47946_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Quake"),
        ("_rsv_47947_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Tornado"),
        ("_rsv_47947_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Tornado"),
        ("_rsv_47951_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Chaotic Flood"),
        ("_rsv_47951_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Chaotic Flood"),
        ("_rsv_47952_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Maddening Orchestra"),
        ("_rsv_47952_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Maddening Orchestra"),
        ("_rsv_47953_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Maddening Orchestra"),
        ("_rsv_47953_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Maddening Orchestra"),
        ("_rsv_47954_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Flare"),
        ("_rsv_47954_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Flare"),
        ("_rsv_47955_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Chaotic Flare"),
        ("_rsv_47955_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Chaotic Flare"),
        ("_rsv_47956_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Holy"),
        ("_rsv_47956_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Holy"),
        ("_rsv_47957_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Flare Diffusion"),
        ("_rsv_47957_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Flare Diffusion"),
        ("_rsv_47958_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Chaotic Holy"),
        ("_rsv_47958_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Chaotic Holy"),
        ("_rsv_48333_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Black Spark"),
        ("_rsv_48333_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Black Spark"),
        ("_rsv_48486_-1_1_0_0_SE2DC5B04_EE2DC5B04", "White Hole"),
        ("_rsv_48486_-1_1_0_1_SE2DC5B04_EE2DC5B04", "White Hole"),
        ("_rsv_49742_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Catastrophic Choice"),
        ("_rsv_49742_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Catastrophic Choice"),
        ("_rsv_49743_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Catastrophic Choice"),
        ("_rsv_49743_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Catastrophic Choice"),
        ("_rsv_49752_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Meteor"),
        ("_rsv_49752_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Meteor"),
        ("_rsv_49753_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Bowels of Agony"),
        ("_rsv_49753_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Bowels of Agony"),
        ("_rsv_49769_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Flood"),
        ("_rsv_49769_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Flood"),
        ("_rsv_49878_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Trance"),
        ("_rsv_49878_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Trance"),
        ("_rsv_49884_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Kefka Says"),
        ("_rsv_49884_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Kefka Says"),
        ("_rsv_49890_-1_1_0_0_SE2DC5B04_EE2DC5B04", "the Decisive Battle"),
        ("_rsv_49890_-1_1_0_1_SE2DC5B04_EE2DC5B04", "the Decisive Battle"),
        ("_rsv_49891_-1_1_0_0_SE2DC5B04_EE2DC5B04", "the Decisive Battle"),
        ("_rsv_49891_-1_1_0_1_SE2DC5B04_EE2DC5B04", "the Decisive Battle"),
        ("_rsv_49892_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Aetherlink"),
        ("_rsv_49892_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Aetherlink"),
        ("_rsv_49893_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Aetherlink"),
        ("_rsv_49893_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Aetherlink"),
        ("_rsv_50066_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Flood of Naught"),
        ("_rsv_50066_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Flood of Naught"),
        ("_rsv_50067_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Flood of Naught"),
        ("_rsv_50067_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Flood of Naught"),
        ("_rsv_50068_-1_1_0_0_SE2DC5B04_EE2DC5B04", "White Antilight"),
        ("_rsv_50068_-1_1_0_1_SE2DC5B04_EE2DC5B04", "White Antilight"),
        ("_rsv_50069_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Black Antilight"),
        ("_rsv_50069_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Black Antilight"),
        ("_rsv_50070_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Edge of Death"),
        ("_rsv_50070_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Edge of Death"),
        ("_rsv_50081_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Flood of Naught"),
        ("_rsv_50081_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Flood of Naught"),
        ("_rsv_50082_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Flood of Naught"),
        ("_rsv_50082_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Flood of Naught"),
        ("_rsv_50545_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Earthquake"),
        ("_rsv_50545_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Earthquake"),
        ("_rsv_50546_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Earthquake"),
        ("_rsv_50546_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Earthquake"),
        ("_rsv_50718_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Meteor"),
        ("_rsv_50718_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Meteor"),
        ("_rsv_50719_-1_1_0_0_SE2DC5B04_EE2DC5B04", "Bowels of Agony"),
        ("_rsv_50719_-1_1_0_1_SE2DC5B04_EE2DC5B04", "Bowels of Agony"),
    ];

    // RSV values carrying raw SeString payload bytes (not valid UTF-8); base64 of the
    // exact value bytes, fed to AddRsvString unchanged.
    private static readonly (string Key, string ValueBase64)[] RsvRaw =
    [
        ("_rsv_4887_-1_1_1_0_S74CFC3B0_E74CFC3B0", "UGh5c2ljYWxseSB3b3VuZGVkIGFuZCB0YWtpbmcgZXh0cmEgZGFtYWdlIGZyb20gAkgE8gH0AwJJBPIB9QNXaGl0ZSBBbnRpbGlnaHQCSQIBAwJIAgEDLg=="), // Physically wounded and taking extra damage from .H......I.....White Antilight.I....
        ("_rsv_4887_-1_1_1_1_S74CFC3B0_E74CFC3B0", "UGh5c2ljYWxseSB3b3VuZGVkIGFuZCB0YWtpbmcgZXh0cmEgZGFtYWdlIGZyb20gAkgE8gH0AwJJBPIB9QNXaGl0ZSBBbnRpbGlnaHQCSQIBAwJIAgEDLg=="), // Physically wounded and taking extra damage from .H......I.....White Antilight.I....
        ("_rsv_4888_-1_1_1_0_S74CFC3B0_E74CFC3B0", "U3Bpcml0dWFsbHkgd291bmRlZCBhbmQgdGFraW5nIGV4dHJhIGRhbWFnZSBmcm9tIAJIBPIB9AMCSQTyAfUDQmxhY2sgQW50aWxpZ2h0AkkCAQMCSAIBAy4="), // Spiritually wounded and taking extra damage from .H......I.....Black Antilight.I...
        ("_rsv_4888_-1_1_1_1_S74CFC3B0_E74CFC3B0", "U3Bpcml0dWFsbHkgd291bmRlZCBhbmQgdGFraW5nIGV4dHJhIGRhbWFnZSBmcm9tIAJIBPIB9AMCSQTyAfUDQmxhY2sgQW50aWxpZ2h0AkkCAQMCSAIBAy4="), // Spiritually wounded and taking extra damage from .H......I.....Black Antilight.I...
        ("_rsv_5078_-1_1_1_0_S74CFC3B0_E74CFC3B0", "V2hlbiB0aGlzIGVmZmVjdCBleHBpcmVzLCBldmVyeW9uZSBlbHNlIGluIHRoZSBpbW1lZGlhdGUgdmljaW5pdHkgd2lsbCB0YWtlIGRhbWFnZS4gU2hvdWxkIGFueSBwbGF5ZXJzIHRha2UgZGFtYWdlLCB0aGUgAkgE8gH6AwJJBPIB+wNEb3VibGUtdHJvdWJsZSBUcmFwAkkCAQMCSAIBAyB3aWxsIGJlIHBhc3NlZCB0byBvbmUgb2YgdGhlbS4="), // When this effect expires, everyone else in the immediate vicinity will take dama...
        ("_rsv_5078_-1_1_1_1_S74CFC3B0_E74CFC3B0", "V2hlbiB0aGlzIGVmZmVjdCBleHBpcmVzLCBldmVyeW9uZSBlbHNlIGluIHRoZSBpbW1lZGlhdGUgdmljaW5pdHkgd2lsbCB0YWtlIGRhbWFnZS4gU2hvdWxkIGFueSBwbGF5ZXJzIHRha2UgZGFtYWdlLCB0aGUgAkgE8gH6AwJJBPIB+wNEb3VibGUtdHJvdWJsZSBUcmFwAkkCAQMCSAIBAyB3aWxsIGJlIHBhc3NlZCB0byBvbmUgb2YgdGhlbS4="), // When this effect expires, everyone else in the immediate vicinity will take dama...
        ("_rsv_5350_-1_1_1_0_S74CFC3B0_E74CFC3B0", "AkgE8gH0AwJJBPIB9QNGbGFyZSBEaWZmdXNpb24CSQIBAwJIAgEDIHdpbGwgYWN0aXZhdGUgd2hlbiB0aGlzIGVmZmVjdCBleHBpcmVzLg=="), // .H......I.....Flare Diffusion.I....H... will activate when this effect expires.
        ("_rsv_5350_-1_1_1_1_S74CFC3B0_E74CFC3B0", "AkgE8gH0AwJJBPIB9QNGbGFyZSBEaWZmdXNpb24CSQIBAwJIAgEDIHdpbGwgYWN0aXZhdGUgd2hlbiB0aGlzIGVmZmVjdCBleHBpcmVzLg=="), // .H......I.....Flare Diffusion.I....H... will activate when this effect expires.
        ("_rsv_5351_-1_1_1_0_S74CFC3B0_E74CFC3B0", "AkgE8gH0AwJJBPIB9QNDaGFvdGljIEhvbHkCSQIBAwJIAgEDIHdpbGwgYWN0aXZhdGUgd2hlbiB0aGlzIGVmZmVjdCBleHBpcmVzLg=="), // .H......I.....Chaotic Holy.I....H... will activate when this effect expires.
        ("_rsv_5351_-1_1_1_1_S74CFC3B0_E74CFC3B0", "AkgE8gH0AwJJBPIB9QNDaGFvdGljIEhvbHkCSQIBAwJIAgEDIHdpbGwgYWN0aXZhdGUgd2hlbiB0aGlzIGVmZmVjdCBleHBpcmVzLg=="), // .H......I.....Chaotic Holy.I....H... will activate when this effect expires.
        ("_rsv_5453_-1_1_1_0_S74CFC3B0_E74CFC3B0", "TmVhcmx5IHJlZHVjZWQgdG8gbm9uYmVpbmcsIGxvd2VyaW5nIHJlc2lzdGFuY2UuIEZ1cnRoZXIgZXhwb3N1cmUgdG8gAkgE8gH0AwJJBPIB9QNOb3RoaW5nbmVzcwJJAgEDAkgCAQMgd2lsbCByZXN1bHQgaW4gS08u"), // Nearly reduced to nonbeing, lowering resistance. Further exposure to .H......I.....
        ("_rsv_5453_-1_1_1_1_S74CFC3B0_E74CFC3B0", "TmVhcmx5IHJlZHVjZWQgdG8gbm9uYmVpbmcsIGxvd2VyaW5nIHJlc2lzdGFuY2UuIEZ1cnRoZXIgZXhwb3N1cmUgdG8gAkgE8gH0AwJJBPIB9QNOb3RoaW5nbmVzcwJJAgEDAkgCAQMgd2lsbCByZXN1bHQgaW4gS08u"), // Nearly reduced to nonbeing, lowering resistance. Further exposure to .H......I.....
        ("_rsv_45500_-1_1_0_0_S13095D61_E13095D61", "AhICNwNUaGlzIGlzIG15IGZpcnN0IHRpbWUsIHNvIHBsZWFzZSB0YWtlIGl0IGVhc3khAhICOAM="), // ...7.This is my first time, so please take it easy!...8.
        ("_rsv_45500_-1_1_0_1_S13095D61_E13095D61", "AhICNwNUaGlzIGlzIG15IGZpcnN0IHRpbWUsIHNvIHBsZWFzZSB0YWtlIGl0IGVhc3khAhICOAM="), // ...7.This is my first time, so please take it easy!...8.
        ("_rsv_45501_-1_1_0_0_S13095D61_E13095D61", "UXVpY2ssIG5vdyEgTWFrZSB5b3VyIHBlYWNlIHdpdGggZGVhdGghAhABA0JlY2F1c2UgSSdtIG1ha2luZyB5b3VyIGRlYXRoIHdpdGggYWxsIHRoZXNlIHBpZWNlcyE="), // Quick, now! Make your peace with death!....Because I'm making your death with al...
        ("_rsv_45501_-1_1_0_1_S13095D61_E13095D61", "UXVpY2ssIG5vdyEgTWFrZSB5b3VyIHBlYWNlIHdpdGggZGVhdGghAhABA0JlY2F1c2UgSSdtIG1ha2luZyB5b3VyIGRlYXRoIHdpdGggYWxsIHRoZXNlIHBpZWNlcyE="), // Quick, now! Make your peace with death!....Because I'm making your death with al...
        ("_rsv_45502_-1_1_0_0_S13095D61_E13095D61", "RGlkIHlvdSB0aGluayB5b3UnZCB3b24/AhABA09oIG5vIG5vIG5vLCB3ZSd2ZSBvbmx5IGp1c3QgYmVndW4h"), // Did you think you'd won?....Oh no no no, we've only just begun!
        ("_rsv_45502_-1_1_0_1_S13095D61_E13095D61", "RGlkIHlvdSB0aGluayB5b3UnZCB3b24/AhABA09oIG5vIG5vIG5vLCB3ZSd2ZSBvbmx5IGp1c3QgYmVndW4h"), // Did you think you'd won?....Oh no no no, we've only just begun!
        ("_rsv_45503_-1_1_0_0_S13095D61_E13095D61", "U3RpbGwgYWxpdmU/IFVuYmVsaWVlZXZhYmxlIQIQAQNJIHJlYWxseSBtdXN0IGluc2lzdCB5b3UgZGllIQ=="), // Still alive? Unbelieeevable!....I really must insist you die!
        ("_rsv_45503_-1_1_0_1_S13095D61_E13095D61", "U3RpbGwgYWxpdmU/IFVuYmVsaWVlZXZhYmxlIQIQAQNJIHJlYWxseSBtdXN0IGluc2lzdCB5b3UgZGllIQ=="), // Still alive? Unbelieeevable!....I really must insist you die!
        ("_rsv_45506_-1_1_0_0_S13095D61_E13095D61", "TGlmZS4uLiBEcmVhbXMuLi4gSG9wZS4uLgIQAQNXaGVyZSBkbyB0aGV5IGNvbWUgZnJvbT8gQW5kIHdoZXJlIGRvIHRoZXkgZ28/"), // Life... Dreams... Hope.......Where do they come from? And where do they go?
        ("_rsv_45506_-1_1_0_1_S13095D61_E13095D61", "TGlmZS4uLiBEcmVhbXMuLi4gSG9wZS4uLgIQAQNXaGVyZSBkbyB0aGV5IGNvbWUgZnJvbT8gQW5kIHdoZXJlIGRvIHRoZXkgZ28/"), // Life... Dreams... Hope.......Where do they come from? And where do they go?
        ("_rsv_45510_-1_1_0_0_S13095D61_E13095D61", "SGFoYWhhISBIb29rLCBsaW5lLCBhbmQgAhoCAgNzdGlua2VyAhoCAQMh"), // Hahaha! Hook, line, and .....stinker.....!
        ("_rsv_45510_-1_1_0_1_S13095D61_E13095D61", "SGFoYWhhISBIb29rLCBsaW5lLCBhbmQgAhoCAgNzdGlua2VyAhoCAQMh"), // Hahaha! Hook, line, and .....stinker.....!
        ("_rsv_45514_-1_1_0_0_S13095D61_E13095D61", "VGhpcyBpcyBtZWFudCB0byBiZSBvdXIgAhoCAgN1bHRpbWF0ZQIaAgEDIGVuY291bnRlci4uLg=="), // This is meant to be our .....ultimate..... encounter...
        ("_rsv_45514_-1_1_0_1_S13095D61_E13095D61", "VGhpcyBpcyBtZWFudCB0byBiZSBvdXIgAhoCAgN1bHRpbWF0ZQIaAgEDIGVuY291bnRlci4uLg=="), // This is meant to be our .....ultimate..... encounter...
        ("_rsv_45519_-1_1_0_0_S13095D61_E13095D61", "SSdtIHRhbGtpbmcgdG8gAhoCAgN5b3UCGgIBAywgb2YgY291cnNlISBZLk8uVS4h"), // I'm talking to .....you....., of course! Y.O.U.!
        ("_rsv_45519_-1_1_0_1_S13095D61_E13095D61", "SSdtIHRhbGtpbmcgdG8gAhoCAgN5b3UCGgIBAywgb2YgY291cnNlISBZLk8uVS4h"), // I'm talking to .....you....., of course! Y.O.U.!
        ("_rsv_45541_-1_1_0_0_S13095D61_E13095D61", "SXQncyBub3QgZW5vdWdoLi4uAhABA0kgbXVzdCBkZXN0cm95IG1vcmUh"), // It's not enough.......I must destroy more!
        ("_rsv_45541_-1_1_0_1_S13095D61_E13095D61", "SXQncyBub3QgZW5vdWdoLi4uAhABA0kgbXVzdCBkZXN0cm95IG1vcmUh"), // It's not enough.......I must destroy more!
        ("_rsv_45542_-1_1_0_0_S13095D61_E13095D61", "RGVzdHJ1Y3Rpb24uLi4CEAEDRGVzdHJ1Y3Rpb24gaXMgd2hhdCBtYWtlcyBsaWZlIHdvcnRoIGxpdmluZyE="), // Destruction.......Destruction is what makes life worth living!
        ("_rsv_45542_-1_1_0_1_S13095D61_E13095D61", "RGVzdHJ1Y3Rpb24uLi4CEAEDRGVzdHJ1Y3Rpb24gaXMgd2hhdCBtYWtlcyBsaWZlIHdvcnRoIGxpdmluZyE="), // Destruction.......Destruction is what makes life worth living!
        ("_rsv_45544_-1_1_0_0_S13095D61_E13095D61", "TGlmZS4uLiBMb3ZlLi4uIFBhc3Npb24uLi4CEAEDQWxsIHdvcnRobGVzcy4uLg=="), // Life... Love... Passion.......All worthless...
        ("_rsv_45544_-1_1_0_1_S13095D61_E13095D61", "TGlmZS4uLiBMb3ZlLi4uIFBhc3Npb24uLi4CEAEDQWxsIHdvcnRobGVzcy4uLg=="), // Life... Love... Passion.......All worthless...
        ("_rsv_45548_-1_1_0_0_S13095D61_E13095D61", "Q29uZ3JhdHVsYXRpb25zLi4ueW91IGxvc2UhIFRyeSBzb21ldGhpbmcgZWxzZSBuZXh0IHRpbWUgYW5kIG1heWJlIHdlJ2xsIGhhdmUgc29tZSACGgICA3JlYWwCGgIBAyBmdW4h"), // Congratulations...you lose! Try something else next time and maybe we'll have so...
        ("_rsv_45548_-1_1_0_1_S13095D61_E13095D61", "Q29uZ3JhdHVsYXRpb25zLi4ueW91IGxvc2UhIFRyeSBzb21ldGhpbmcgZWxzZSBuZXh0IHRpbWUgYW5kIG1heWJlIHdlJ2xsIGhhdmUgc29tZSACGgICA3JlYWwCGgIBAyBmdW4h"), // Congratulations...you lose! Try something else next time and maybe we'll have so...
    ];

    // RSF: exact 0x48-byte RsfReceive records (unlock locked model/VFX/sound files).
    private static readonly string[] RsfRecords =
    [
        "YlSAP126o6x42uy9D1hbZZ42fAyrQ8PU1p26ZXb3mo2dt2MapMC87Vjc2XbQ3Zmh7n5rOx7SppJondaW6triYCsMJIKOlaLd", // bT.?]...x...X[e.6|..C....ev.....c.....X..v....~k;...h.....`+.$.....
        "r/iQWV26o6x42uS9f3QU150nWrTGttQdwZx3Yidn1jvSYANyy5Ly5tjgxUTNkn8yydkNk7gQg0GtcU7eS8Qk1jjLoBFG3RYv", // ...Y]...x...t..'Z......wb'g.;.`.r......D..2.......A.qN.K.$.8..F../
        "FKI8w126o6x42uy9C3gT15k3PhWbBuxA/ts2TXe3myGkBCIHnN1N6iwJmVz+X5pLk9I0Y7lg+7hcEvAFHCRjRyP5KJYIYNmQ", // ..<.]...x...x..7>....@..6Mw..!.."...M.,..\._.K..4c.`..\....$cG#.(..`.
        "vLNi/5mmw/142uy9B1QUS7v324DAZHIUMUcMgxiZqpnHnMWcFQETYkAUs4IKKuaICpgVM6CY6RowYlYMG7PbjDlHVG5PD3Rh", // ..b.....x...T.K....dr.1G...........b@....*....3....0bV....9GTnO.ta
        "USFUEBNseLJ42uy9DVhU5533fxzEkKEp9skmofnvvzsmYmYGI0zf4rhpcGh8GWx3YXRAj0YUq8KQtAbMxkKUERJfINvsrrJ1", // Q!T..lx.x...XT......)..&...;&bf.#L..iph|.lwat@.F.......B..._ ..u
        "lqB7eRNseLJ42uydDXwcVbn/z0y2SWZpm01AqJbaoWxpiyCoEC+gZAsRdyrQirqXe/GlLxhASYN4rXq1JAQvJHix2yXyQXkp", // ..{y.lx.x...|.U...L.Ifi.M@...li. ../.d..w*...{./.@I.x.z.$./$x..%.Ay)
        "nI1EdhNseLJ42uy9C3Acx5kmWGiKMtkwh7MTy/Xsxa6LevChxlCIu1jZtx6PCnr7ETvLmFGxOTSFgiiJ1mDmbhTe04iGRqwS", // ..Dv.lx.x...p..&Xh.2.0........z..P..X....z..;.Q.94..(..`.n....F..
        "J9fo7BNseLJ42uy9D3xbxZXof1GWlsjr5v22S/s+bXeHwqYQGce7bUP28W+y9LevXWh/ZEsUp47jSWNnH7WUklpya3TljCIp", // '....lx.x...|[...Q.......K.>mw.....mC..o....]h.dK....Icg....Zrkt.")
        "KXgUgNtQhW542rS8C3gb13km/J2ZAUgRmAsuFB2LAGYAULIjERgApNjEEjEgKSdtYhKklGSf/VuLlJNut21iknLip+kmZnrd", // )x...P.nx...x..y&....H........f.P.#.......1 )'mb...d..[...n.mb.r..&fz.
        "nZqYPNtQhW542rS7DXzb1nkv/BwApGSJwDkAKSmJLRIAKbtJLBGkZKtpbIuU5GRbG5uS3fV2W2PZTrt322+LZCft9m5r1Ht3", // ...<.P.nx...|..y/....d..9.)).-..).I,..d.il...d[.....v[c.N.w.o.d'..nk.{w
        "sJIcH9tQhW542rS8D3gb13Uneu7MgKQIzNwZABRliQQGACk6lgAMAFJybJEASMpO40gEKSfZNo1Iytk0fdtapOS2ry/bmEna", // .....P.nx...x..u'z.........e....):....Rrl..H.N.H.)'.6.H..4}.Z../.I.
        "mb+eT9tQhW542sy7D3Qb13kn+t0ZgKQIzNw7A5B0LBGYAUDSsSRiAPBPaksEQFJ2ksYiSMlJ+5pYpJx0X7snMSnK8dnsbqO0", // ...O.P.nx...t..y'........;..t,...@.$b..OjK.@Rv.."H.I..X..t_.'1)....n..
        "t3i+TNtQhW542rS6D3Qb13kv+N07A4AiMXPvDEDJtkhgAJCiG4nEAKSkJJZIgJTstLFEkHLSZptYpNS813ZfIpJSkrb7YtN9", // .x.L.P.nx...t..y/..;.."1s..@.H`.........$.H...D.r.f.X...v_".R...b.}
        "A5oy8NtQhW542rS7DXgb13nn+54ZDEkRmDlnBqBoxyIxM6DEfEjEACClfFgkAFJ2toklkHQ+umksUkq2d9sm5occP9t2E7V9", // ..2..P.nx...x..y.....I..9g..h."13..|H.. .|X$.Rv..%.t>.i,RJ.w.&..?.v..}
        "LpK209tQhW542rS7DXgb13ku+J35ISliZs4ZABRtmQQGACk5kUgMSEpMbJEEScn5qSWClJM0jW2Rcpumt0lMSnZ9025jpu22", // .....P.nx...x..y....!)bf....m....)9.H.HJLl..I...%...4.m.r...ILJv}.nc...
        "B780g9tQhW542sy7DXQb53nn+7wzGFIiMPO+MwDFxBaBmQEoJbFFDj4oJrEt4oO00iax+CEl293WJinH3Ww/IpFylPbebtQm", // ..4..P.nx...t..y...3.R"0.3.......(%.E.>(&.-..&..!%...&)..l?".r...n.&
        "VH8xwttQhW542rS8C3gb130n+j9nBnxi5pwBING2SGAAkKItkcQAJCXbEkmQlNwktkiQctKmiUXSbnL7tbFNSk663W0sOt37", // T.1..P.nx...x..}'.?g.|b.. .H`...-...$%..I...$.H.r..E.nr...MJN..m,:..
        "4J29fttQhW542rS7DXgb530n+H/nA5QIzLzvDEAytiVgBgAlx5aIAUCKdmyTAEjJ3SS2QFJJ9243EUXZ1/b2npqkZPva7qbM", // ...~.P.nx...x..}'.........@2.%`..%...@.vl..H..$.@RI.n7.E.......d....
        "zZU5XdtQhW542sy8DXgb13km+p0zM6REYOacGYCkbYnA4IdiYovAACRFJ5bI4Y+S28aWQMpNb39sUbLbu91uIlKym91tN2a6", // .9].P.nx...x..y&..33.D`....m....bb...$E'.....@.Mo.lQ...n"R...m7f.
        "5Li7DdtQhW542rS7C3Qc13nn+d2qbgAEuureqm4QehDoquoG4FgkuvoBwOOYRD9AyrFiEg8q3snYEgBq4k02icCHpcnOyZg+", // ...P.nx...t..y...n.....n.z.....X$.....D?@.b..*.....j.M6.......>
        "yn+bDttQhW542rS6C3wb13kv+J0zMyQlYGbOACBpWyIweFB0IhIYgJTkxhIJPqxk40gEKSdpcmMJkrvb9ja1Scqxu93Wpttt", // .....P.nx...|..y/..33$%`f.. i["0xPt"........>.d.H.)'irc.....6.I.....m
        "fp0XsttQhW542rS8DXQb130n+r93MKBEYObeGZBiYonAACDFNJaIAUCKiWOJAEjZ2XyIIKn0uxZFOd1+7LNJSrabdpuo3e1r", // ~....P.nx...t..}'..w0.D`....bb... .4...@..c..H..|. ....E9.~.IJ..v....k
        "U5WTkdtQhW542rS6DXQb13Xvu88ZDCkRmDlnBqToDxGYAUAyiUViAJJiEkskQMp2mtgiSClfTWxRkt20r70RP2T7prerZtrb", // S....P.nx...t..u....)..9g.......@2.Eb..b.K$@.v.."H)_MlQ.....?d....f..
        "ergRwdtQhW542sy7C3Qb2Xnn+d0qFCkRqKpbBVBsu0WgqgCKsdsiniRtt1vEg5Kch1t8yM5mdjwWqW7nNRNLotRKsnkou3nY", // z....P.nx...t..y...*.)...[.Pl.E......".$m.[....[|..fv<..n.5.K..J.y(.y.
        "03ZeBNtQhW542rS8DXQb13Uuus/8kBQxM+fMACRdiwQGACnalggMQEpKbJEASdluEksEKbv3NWkkSk562740AiUnfm1vY7pt", // .v^..P.nx...t..u......13...$]....)...@JJl..I.n.K.)..5i$JNz.4.%'~moc.m
        "Z5TSuNtQhW542rS7CXgb13ku/J0ZDCkRmDlnBqTo2CIwA3BJY5MYAJSY2JYIkJLcJbZISkm6JDYl2U1vl4SLbN3e+6dR0ts0", // g...P.nx...x..y.....)..9g...."0.pIc..........%.HJI.$6%.Mo...l....Q..4
        "SpxWm9tQhW542rS8C3Qb13ku+u8ZDCkRmNl7BqDo2CIxMwDFNJaIAUCKeVgiANJ2myYSSMlxT9NapJQ2vaenDSn60bQ9jXr6", // J.V..P.nx...t..y.....)...{...."13..4...@.yX"..v.&.H.qO.Z..6....)..=.z.
        "Y7HUy9tQhW542ty8e3Qb2X3n+bsFlB4kUC+ApNu2iHoA4iS2xUIVQE7WDxEPduflWATYjjfrTFpkO6/1bFokZeUxu+lMJmfs", // c....P.nx..{t..}......$P/....z..$..B.@N....v..X..7.LZd;..lZ$e.1..L&g.
        "TXb0yNtQhW542rS8DXQb13Uuus+ZGZIiMXPOAKBoRyIw+KEY2xIxACkxtSUSICU7r7FEULLTn8QWJSdtb5vGpOQkTdPGTPtW", // Mv...P.nx...t..u....."1s...hG"0.....1.)1.%. %;..DP....%'mo...$M..L.V
        "+ZR4dNtQhW542rS7DXgb13km+p0ZDEkRmDlnBqBkWyQwMwBFN5aIAUBKiW2JAEnJaRKLf4632yY2JSXbe7ttTFJyvNvu09DZ", // ..xt.P.nx...x..y&....I..9g..d[$03.E7...@J.m..I.i......&6%%.{.mLRr......
        "1Jz8V9tQhW542rS7DXwU13kv/Jwzs5LQ7sw5M7sCbNDu7IeQHSPt7K6AJDbSrgR2mthoBSR5mzZGYKdN+mFLgOO2t62V3n6k", // ..W.P.nx...|..y/..3.....93..l....#..$6..v..h.$y.6F`.M.aK.....~.
        "/bF+B9tQhW542rS7DXTb1p0n+r8AIckigXsBUFYTWyRAUlaaWCJISnY/bAmU5KTTaSxK7rTzuhNbctrudmc3keSk6c7stOru", // ..~..P.nx...t..'...!.".{.PV.[$@RV.X"HJv?l....i,J...[r..vg7.......
        "rnF7RttQhW542rS8DXQb13km/N47GJIiMHPvDEjJtkhgAJBibInAAKTExBZJgJTsbGyLoOQkbWNblJz22zYbm6ScddOmNZN2", // .q{F.P.nx...t..y&..;.."0s..H.H`..bl.......I...ll...$mc[....6....u.5.v
        "GpP3+ttQhW542rS8C3zc1nkn+p0DgJRIAOcAMxRtS5zBPCTZlsjBDEkpji1y+LCdTWxxSDpN06YmJee2vXc3NinJyWZzEzPN", // .....P.nx...|..y'.....H...3.mK..<$....I).-r...MlqH:M.&%.w76)..fs.3.
        "N5tz2dtQhW542rS7DXQb130n+r93BqREYObeAUDSsUhg8EExtkhgAJJSHEskSMpOsolEkHaS021iUnLSbbddm5SUptu8tZn0", // 7.s..P.nx...t..}'..w..D`...@.H`.A1.H`..R.K$H.N..D.v..mbRr.m.]........
        "HrbxidtQhW542sy8D3Qb133v+bszGFIkMHPvDEDRsUVi8Idkk0jEACDF/LFEAKSUtLFNgJST0742Jmk3aU+blqRke/P6J3rZ", // ....P.nx...t..}...3.R$0s..@.Eb..d.H.. ...D.....M....6&i7iO...d{..'z.
        "MHHRittQhW542rS7DXgb13km+p0zA1IkMHPODEDJtkhgAJBSYpHAACDFJLZIgJTs3sYWQUpOb9PEomSn3W6biJScpE3Tmknb", // 0q..P.nx...x..y&..3.R$0s..@.H`..Rb... .$.H......AJNo..d..n.....M.I.
        "hJNdNttQhW542rS8C3Qb530n+v++GYASMTPfDACKtiUCgwfFJhaBAUiKTWyRA1Ky03UsgpScpGkrkXKy2e3DJinH2Z5tE2Zv", // ..]6.P.nx...t..}'......13.....%....&...H.Ml..R..u,....i+.r....&)..m.fo
        "qZvZFdtQhW542rS7C3wb13kn+p0zM6REYOacAUDRlkhg8KBoRyQxACgxsSUCJCW7bSwSpPLoI7YoKWm2aWuTkpw0+2ttutv0", // .....P.nx...|..y'..33.D`..@.H`.hG$1.(1.%.$%.m,....#.()i.ik...4.km...
        "gLZbRdtQhW542rS7C3gb130v+D9nBqBEYGbODEDSjkhgAJCSHyIwAEjJsUViQFJ22koiKDm9vW1skbK7ve1tIoqy4/beNmLS", // ..[E.P.nx...x..}/.?g..D`f..@.H`...."0.H.Eb@Rv.J"(9..ml.....m".....6b.
        "nGPxU9tQhW542rS7C3gbx30v+p/ZBUkR2J3ZBSg5FoldAKQYWyKwACnJsSQSJGUnaSwRpJTHycOi5DRp0xsLlJzkJPfEptOm", // .c.S.P.nx...x..}/....I....(9..]...["..).$.$e'i,.......4i......$...
        "KIF979tQhW542rS8C3wb13kn+p0ZDCmRmDlnBqDoB0nMAKDoh0gOHhR3Y0sEQEpOU1viQ06auxubpNzu3u5uQlJy3GzaRunt", // (.}..P.nx...|..y'....)..9g....I....H...wcK.@JNS[.CN.........nBRr.l.F..
        "BYn5zNtQhW542rS7C3wb13kn+p0ZDEkRmDlnBiBpWyIxAEjRiURgAJJSGlskQEp2W9siSMnuK5Eoydlfd29rk5QS7+5t1nS2", // .....P.nx...|..y'....I..9g. i["1.H.D`..R.[$@Jv[."H..+.(.._wok.....m.t.
        "LKR7nNtQhW542sy8C3Qb13ku+u8ZDCmRmNl7BiAZ2xIxD1BKYkvEi1JjWyIelNw0iUWCktO0TSxRTtLHzYlEyXFPmybq47Sp", // ,.{..P.nx...t..y.....)...{. ...1.PJbK.Rc["...4.E...M,QN...D.qO.&..
        "AmNbn9tQhW542sy8C3wb13kv+J0zA76AmXNmAJK2RAIDgBQdSyQGICU5tkSCpGy3jSWBktN2N7FFyU7bmyY2SNnJ3Zu2Zrx3", // .c[..P.nx...|..y/..3....sf...D.....K$. %9.D..l..%...v7.E.N.&6H....f.w
        "toHXI9tQhW542rS7D3gb13Uneu7MAJQIzNw7A1C0IxEYDEgpiSViAJBiE1skQFJymtgSSMrJe+0mIimn3falNUkpdvveJlGa", // ...#.P.nx...x..u'z.......;.P.#...H).%b..b.[$@Rr...H..{.&")....5I)v..&Q.
        "m4lTANtQhW542rS8C3wb13kn+p0ZDEmRmDlnAFC0LRGYAUDRsUViAJBiEkskCFL2trFFkJKTvmxRcvpKm5iSnPh2txsre3/d", // ..S..P.nx...|..y'....I..9g.P.-...@.Eb..b.K$.R...E....lQr.J.....v..+{..
        "sqTRUNtQhW542rS7C3Tc9n3n+/sDA1ISB8AfwFBsYouDx5BMGoucAYZk2sTWPCi5m9YxZyin7fa2ESknbW8fkUg7bvfcbtXH", // ...P.P.nx...t..}.....R.....Plb...L.....d...<(...1g(.....)'mo..H;n..n..
        "7ESZudtQhW542rS8DXgb13km+p0ZDEkRmDlnBqToWCQwAEgxtkRgAJJSEkvkkJTsNLFEULLTu21sUbK7P+2NBUpy0p/dmG67", // .D...P.nx...x..y&....I..9g...X$0.H1.D`..R.K..4.DP..mlQ..?..Jr..n.
        "WKYVBdtQhW542rS8DXgb13km+p0ZDEmRmDlnBqAYWyIxA4Ck40jEAKDE/FgiANJKmsYSSNnxtk0sUkrSXvfemD+y3TRPE+7u", // X....P.nx...x..y&....I..9g...["1....H.....X"..J...H..M,RJ.^..?..4O...
        "da6RJttQhW542rS6C3wb133n+z9nZkiRwMw5A4CiY4nA4CHJD5EY8CE5sUQOSNnexrYIUk66TRMJlJJ2u7eJScpJH7etmW4f", // u..&.P.nx...|..}..?gfH...9...c...!.....!9.D.H....RN.M....v...I.I....n.
        "XIMTdttQhW542sy7D3Qb133n+7szGFAiMHPvDEDStkRgBgDFxJaIwR9KbWyL+EPJ2TYWQVJOetrEoqike3bb1/CPHKft6Vrd", // \..v.P.nx...t..}...3.P"0s..@.D`.......Jml..C..6.ARNz....{v........Z.
        "ckQzddtQhW542rS7C3gb13UuuvaeAV/AzN4DgKJtEcAAICXHEoEBSIpJJJFDUnZ6G0sEJSVpz41FSnmd3nNik5KTnpyb2HTy", // rD3u.P.nx...x..u....._......m... %....H.I$.CRvz.K.%%i.EJy..sb.......t.
        "xqa/ydtQhW542rS8C3gb130v+D/zICURM+fMABRtSwRmBqCYxhIxACgxjS0RfMhOk1oESTttbxObpNPm7m0a8yHHbffeRu1t", // ....P.nx...x..}/.?. %.3....mK.f.....1.(1.-.|.N.Z.I;mo......m..!.m..F.m
        "66476ttQhW542rS8C3wb133n+z/zICkCM+fMABRtSwRmAFB0bZEYgKSYxBIJkpLdPCyCpJO099YSKTndbNraJCXHbbqNlT52", // .;..P.nx...|..}..?. ).3....mK.f.Ptm...........<,.......)9.l..$%.m...>v
        "woO5uttQhW542rS7C3Qb130n/L/zACUCM/fOABTtWAQGACk2sUQMAFJMYksEQEpKk1gESDl9JRZJJWn3pIlJSra3aR5K99s2", // ....P.nx...t..}'....%.3.....X...)6.D..RLbK.@JJ.X.H9}%.I%i...IJ..i.J..6
        "kUO8+9tQhW542rS8C3gb53ku+P0zGFIiMfP/MwBFX0RgBiDFOBaJAUCajS8keJGdi22ClHI7J7FIOXna7cUmKSk+6Wkb9tnt", // .C...P.nx...x..y...3.R"1..3.E_D`. .8...@../$x...m..r;'.H9y...&))>.i....
        "JaEwR9tQhW542rS7DXgb13nn+54ZDEkRmHPOACDpWCIxA4CSHVvEACTFJLZIgKTsfFkCSbvZNo1FSmnv7t424Yccp3ubhmm6", // %.0G.P.nx...x..y.....I..s.. .X"1....[..$.$.H...|Y.I..6.EJi...6...{..i.
        "CKm0ZNtQhW542sy7D3gb13Uneu6dGUIiMTN3AFCMLRKYAUjRtkRgAJJSEksEQEp2t7FEkLLTNG0kUmr7+ieJScpONtvXmmmy", // ...d.P.nx...x..u'z..B"13w.P.-...H.D`..R.K.@Jv..D...4m$Rj..'.I.N6..i.
        "IYQ2NNtQhW542rS7C3gb2XXneW4VipREVN1bBZBsd0tAVQEU7VginiSduFvEg+r2OO5uPtR2NmPHfLSdzSSxJUpyT/YxrZns", // !.64.P.nx...x..u.yn...DT.[..lwK@U...X".$..[...8.n>.v6c.|...$.%JrO.1...
        "D0MWN9tQhW542rS7e3wb130n+jtnBuADmDlnAJC0LREYAHzYlkgMQEpybFEASclJ41oEKbvJ3cYSJSfb7u3GIiUn+bTbxky7", // .C.7.P.nx..{|..}'.;g....9g...-...|.H.@JrlQ.I.I.Z.).....%'...."%'....L.
        "u6Gai9tQhW542rS7C3gb130n+j9nZkCJxMw5MwApxxaBAcBHYovEACClJJZIgKScbOKIoCQ3d9vUIuVk+0hjk5Rj9+7dL2Z2", // .....P.nx...x..}'.?gf@...93.).....Gb... .$.H...l.$7w..".d.Hc..c.../fv
        "lqkeqNtQhW542sy8C3gb53ku+P0zACmRmJl/AFB0bRGYAXhJHJEYAKSY2pY4ICk7TWIRJOWkJ20skrK326aJScpOetqm0dm0", // .....P.nx...x..y...3.).....Ptm...xI.......8 );Mb.$.'m,.....I.Nz...
        "v4Sc+NtQhW542rS7C3jb2H0n+j8AIdkWgXMAUlaSsUU8KCtNYosEKSltkhEf0rh5jkh6Ju223bHlSXP7uK0teWaaJreZ9m63", // .....P.nx...x..}'.?.!...s.RV..E<(+Mb..))m....y.Hz&....Is...-yf.&...n.
        "FkrTPdtQhW542rS6f3zb5n3v+30egJIsEngAkLKSWCIBUrKS2BJBUrbSxBZJSU7aJrEo2W23dbUlpzvb2WtN5B9dux9t1O3s", // .J.=.P.nx...|..}..}...,.x....X".R....AR....IIN.&.(.m.u.%.;..kM..]..m...
        "oqhfgdtQhW542rS8C3Qb53nn/bzvzIAUgZl3ZgBSjiUCgwvF2BaJAUiJTSyRACnJ6SUiSNpx26wtUkp2u73EFKUk7fnaNZNu", // .._..P.nx...t..y........wf.R.%........H.M,..)..%"H.q.-RJv.....$...5.n
        "j6DbottQhW542rS6C3Qb13nv++09A1AiMLP3DEDRtkhgAJCiY4nEAKTEJDbJISnZaWuJICWftqeJRcp9nNs2FknJ9k3T2nR6", // ....P.nx...t..y...=.P"0...@.H`...c.....$6.!).ik. %....E.}..6.I..M..tz
        "po1Z8ttQhW542rS7DXjb5n0v+n8BQpIlAu8LkLLSxCIBkJLaJJZAUrLaJrH4ISfdbhNRkrPeu7WNLLfdxz0nlWVn2fZsp96e", // ..Y..P.nx...x..}/...B.%......."....$.@R..&..!'.n.Q.....,...='.eg..l..
        "iEp58dtQhW542rS8D3gb13Uneu6dGVIkMHPvDEDRtkhgAJBSYpHEAKQkJ5IIgJTsNrFEkHKbfttGpOT0z26biKTtZPO+Nqbb", // .Jy..P.nx...x..u'z..R$0s..@.H`..Rb....$'.....6.D.r.~.F....n....d.6..
        "PKj1TdtQhW542rS8C3wbx3kv+s3sLkkR2J3ZBSjalggsAIpMLJFYAKToxJYIkLScNrYFkk56T9pYpJw06U0Tk5If7WkbM2ny", // <..M.P.nx...|..y/....I....(..,..L,.X........6...NzO.X..4.M.....i.3i.
        "EaBxbttQhW542rS7C3gb130v+D8zGFIiMHPODEAqsURiBuAjjSVyAJBiEsskAFJ2HrZEUnJyu20sUkqb9m6TiJRsZ/tI2Db3", // ..qn.P.nx...x..}/.?3.R"0s..@*.Db..#.%r..b..$.Rv..DRrr.m,RJ..n...lg.H.6.
        "OI3zPttQhW542ty6e3wb130n+jsDDGWJwLwASkljEfMAKCexRWAGIOs8LGAASukjNgHQTrdJa4l02tt2s5EoOf7s9hFvu91N", // 8..>.P.nx..{|..}'.;..e....JIc...('.E`. .<,`.J.#6..N.Ik.t..v..(9....o..M
        "a032f9tQhW542rS8f3gbx3ku+s0slpBI7M4sAIq2RQILgJIcSwQWAGU5lkgAlGQntUWCktOkbSxSitP2tIlFSnbTX47oPM29", // kM...P.nx...x..y...,..H..,...E.....K...e9.H..d'.E...m,R.....EJv._..<.
        "3696w9tQhW542rS8DXgb13km+p0zAEmRmDlnBqBoRyLmDEBKcSwSA4CUktoiQVJy2sYyQcpO76aJRclJe3/6xNSP6/a5u9fK", // .z..P.nx...x..y&..3.I..9g..hG"..@Jq,......"ARr..2A.N.E.I{..........
        "8qf+4NtQhW542rS7DXQb130n+r93MCRFYObeGYCkbZHAACBFxxKBAUiKiSWRICXZ2SQWQUppN6+JRcpp032njUjZSdrX3UZJ", // ....P.nx...t..}'..w0$E`.....m... E....H..%. %..$.AJi7..E.i.}..H.I...FI
        "24p8sNtQhW542rS8C3Qb13ku+u8ZDEmRmL33DEDSD5EYPCjGjkUMAFKME1sEQMpqmsTiw+lrNRZFJW1Pe25MUnZ8+0qVNu1N", // .|..P.nx...t..y.....I.....@....<(.E..R..[.@.j.....k5.E%mO{nLRv|.J.6.M
        "9U1cs9tQhW542rS9f2Abx30n+p1dgJRF7M7sgpTsWAQWACW9xBaxBCmrSSwRpGSnTWqLktwm/ZGYkpP09UdiSnab5N1drVx7", // .M\..P.nx...`..}'..]..E....X...%.....).I,..d.Mj...&.......GbJv...].\{
        "Qa/QD9tQhW542rS9CXgc13Umem5VN7ih696qBkgvIrqqGiDjhUQvIBlvIjZKTmJbBCDF73uZZ5OU/bJM4oikbL8kLzNyJsk4", // A....P.nx...x..u&znU7.....H/"... .D/ .o"6JNb[. ..{.g....L.l.$/3r&.8
        "bKdULNtQhW542rS9DXwU15Unem5VNxJSV91b1RI4Bqmru4WJbaRufWDiGKSWACcbGxDgbJKZxAgys++9nRlbYGfym5ndMZO3", // l.T,.P.nx...|..'znU7.RW.[..8......m.n}`.....'....l....2...[`g..1..
        "RYrWfNtQhW542t29D3hc11kn/J47kp3YmnvOvSPH9E+se2dku9vSWDMj24VvE0sjOeUp0NpS4CnbZes4BRb4FhInLP/KkmVh", // E..|.P.nx...x\.Y'..;...{.#..O.{gd...X3#.o.K#9.)..R.).e.8.....',..ea
        "WV98attQhW542rS7C3gb13UuuvaeASgRmNl7AFK0LRIYAKRoWyIwACnRsUQSICUnbSwRpJymaWqLkn2aprexSMpJetqTmElP", // Y_|j.P.nx...x..u.....(...{.R.-....h["0.).D. %'m,....ij..}....H.Iz..IO
        "7b3w1ttQhW542rS7CXwb13kv+p0ZDEkRmDlnBqBoWyIxGIBkYovEYKGUxRIBULabJrZASknatJFIKemW15ikZKu9vbdR0yWb", // .....P.nx...|..y/....I..9g..h["1..db..`.....P..&.@JI..H)...d....Q.%.
        "wLV09dtQhW542rS8fXgb13kn+p6ZAUgRmDlnBqBkWyRmAJCiY4nEACAlf0jkAJScpIlEkFKapptIpJw06SaNScpJ2t6uLXfT", // ..t..P.nx..}x..y'....H..9g..d[$f...c... %.H......D.R...H..4.&.I.I..-w.
        "6Zj2pdtQhW542rS7DXgb13nn+54zA1IiMHNmAFC0LRIYAPyoLZEYAKTYOBLxQcpKE1sESTtNP2KRctLbNm1MUk687d00TL9u", // ....P.nx...x..y...3.R"0sf.P.-.....-.....8..A.J.[.I;M?b.r..6mLRN...4L.n
        "x1/WpttQhW542rS7fXgb13kn+p4zA34BM+cMAEq2RQKDD4qOLQIDkJJiWyJBUnKSOiJByk52m8Sk5DS9bZOYlJzu5m5j0Um3", // ._..P.nx..}x..y'..3.~.3...J.E.....-....b["ARr.:"A.Nv...4.m......nc.I.
        "c71aGttQhW542rS7e3gb533v+XvnAkokZt53AFC0IxIYDEAxcSTiRoq5WCIAUnabJhJIyk1P20SklG4vexKTkh23Z882Spo+", // s.Z..P.nx..{x..}..{..J$f.w.P.#...@1q$.F..X".Rv.&.H.MO.D..n/{.....g.6J.>
        "XrXeOdtQhW542rS7f3gb13nn+54zA5IiMHPOAKDoyAQw+EHRsURiAJJWa0skQEpK20QiSNlJu5tIlOy2m+5tREpxctttK7pP", // ^..9.P.nx...x..y...3.."0s......0.A.Db..VkK$@JJ.D"H.I..H...mDJqr.m+.O
        "d5hcadtQhW542rS6DXgb13km+p0ZgJQIzJwzA5C0IxKYAUAxiUVi8EMxTWQSACk5fdYWQVJKsm1qk5TbTZ+2MUnZcW7bxMo+", // w.\i.P.nx...x..y&.......3...#...@1.Eb.C1Md..)9}..ARJ.mj...M..1I.qn...>
        "r1DirttQhW542rS8DXgbx3ku+s3sgqBI7M4sAEqyJAALgBQdSwQWICU6lkSCP4rTxBJByj5J21gi5Tbnpo0tUrLbp2lr0WlP", // .P..P.nx...x..y....H..,.J.$.....K.. %:.D.?....A.>I.X".6.-R..ik.iO
        "G7JuEttQhW542rS7C3gb130n+j8zGFIiMXPODEDKsURgBgDFPCRyAJKiG1skAFJW85JASnbau0lE0ml7290vISnZbrftWmm7", // ..n..P.nx...x..}'.?3.R"1s..@.D`...<$r....[$.RV.@Jv.ID.i{../!).n..Zi.
        "NrrqMdtQhW542rS7C3gb130n+j9nZkiJwMw5A4CUHZHADECKqSUCA5CSEtsiQVJ2XrYISk7atIlFyX1t27VJyUlvt91YadKv", // 6..1.P.nx...x..}'.?gfH...9.......@..%......"ARv^..JN..E.}m.I.Io..Xi.
        "H5doYdtQhW542rS8C3wb13kn+p0ZjCiRmDlnBiDph0jMDEAxqUVi8KAU15YIgJTdtLHEh5zsblubktJ0t3dTk5QfzW67UR+3", // ..ha.P.nx...|..y'....(..9g. .H..@1.Eb...........n[...t.wS....n.Q..
        "MVBIYttQhW542sy7C3gb130n+j9nZkiRwMw5GICkY5HAACBFOyKJAUlJsS2SICnZedgiKNm76SaWKDnpI01jkLLdx7Yxk9vt", // 1PHb.P.nx...x..}'.?gfH...9...c... E;"..II.-. ).y."(..&.(9.#Mc....1...
        "hbLE3ttQhW542rS7D3wb130n+HtvMKBMYOa9GYCkI4vAACClpJaIAUBKTW2JIEg5bROLIOk0bbe2SDnNddvdmKRsq+1ua6W7", // .....P.nx...|..}'.{o0.L`....#... .....@JMm. H9m.. .4m..H9.u...l..nk..
        "qLpA/dtQhW542rS8C3wb133n+z8zGJIiMHPODEA9SWAAkKITkcAApCTbEgmQkp0mtkSQcpq2txYhOclu87BIyk7b7Y1FZ/vI", // ..@..P.nx...|..}..?3.."0s..@=I`........$......&.D.r....!9.n.H.N..Eg..
        "gZfCrdtQhW542rS7DXgb13km+p0zGFIiMHPODEAxtkliBgDJxBKJAUiKbWyRAEnZbRJLICU7bZpYpOx0u7etQ1Ky3Z/dWNn0", // ....P.nx...x..y&..3.R"0s..@1.Ib.......H.ml..I.m.K %;m.X..t...CR...X..
        "0lfH7NtQhW542rS6e3wb130v+DtnMCRFYuacGYBibInA4EEysSRgAJJSHhIJgJSd3loiSMlJt4ktSk5zN7m3Nikp8bZ3GzNt", // .W...P.nx..{|..}/.;g0$Eb...bl...A2.$`..R.......Z"H.I..-JNs7..6)).w.3m
        "ZrVLUNtQhW542rS7DXgb13km+p0ZDCmRmDlnBqAYWyIxA4BkYkvEACClNpFIEKTstI1FkJSdpttYlOT+3Ge3MUnJdpttu0x7", // f.KP.P.nx...x..y&....)..9g...["1..dbK.. .6.H...E.....X....g.1I.v.m.L{
        "S73Pc9tQhW542rS7C3gbx30v+p9ZLEkR2J3ZBUj6IQILgBSbSAQWACk6tkQCJGWnaSyBlJI0vYlEyml7257aFCXbfdzWTE97", // K..s.P.nx...x..}/..Y,I....H.!.....H...):.D.$e.i,...4..D.i{...%.}..LO{
        "YpBNI9tQhW542rS8D3gb13Uneu4dDEkRmLl3BiDlWCIw+EMpsSRgAJBiElskQEp2XmpLIOX8e9tYpJz2y26bmKScpNmXFyv9", // b.M#.P.nx...x..u'z...I...w. .X"0.C).$`..b.[$@Jv^jK ..{.X....n.......+.
        "TFdtINtQhW542rS7fXgb133n+ztnZkiJwMw5A4CibYrAACDFxBKBAUhKiSURICXbaWOLIGUnm6QWKdltbjeJRUpO0rt1bCbd", // LWm .P.nx..}x..}..;gfH...9...m... .....HJ.%. %.ic. e'...).mn7.EJN.ul&.
        "+LXhnNtQhW542rS6C3gb53nn+34zGFIiMPN9A4CkY5nADMCLY0vEAODFsSUSACmrbWIJpJRsm91YpOS0Pd0mJinJ2Xa7sdJu", // ....P.nx...x..y..~3.R"0.}...c.....cK....%..).mb...l..X..=.&&)..v...n
        "1b1lv9tQhW542rS8DXwbV5kv/Jwzku1YmjlnRnLSNrE0I8kx0MQaSXZcoLHlj7QstLHsALvw0sZOWXb57UJtpyzv7svdunf3", // .e..P.nx...|.W./..3..X.9gFr.6.4#.1...Iv\...,........NYv..Bm.,....w.
        "/JDn79tQhW542rS8DXgb13nn+54ZDCmRmJkzA1KMY5OYGYDiJraIwQAkndgS8UHZaWpbJCg3TbeNRSrpzW5vY4mS4/1oGiXt", // .....P.nx...x..y.....)...3.R.c.....&....$....A.ij[$(7M..E*..noc....h.%.
        "VV6oKttQhW542rS8C3gb13UuuvY8SIrAzN4DgFRsicAAoMTEFokBSJqJJREgKdlpbYug5DQ5TSxCipPT3jY2SdlJ2t5YTPq4", // U^.*.P.nx...x..u...<H......Tl.........H..%. ).im...49M,B....66I.I..XL..
        "4bwklttQhW542rS8C3wb13kn+p15EBKBmXNmAIqOLQIDgBSbWCIGACk2tiUCJGXntrEFknJye5tYJJVHm7QxSdlxuu0myu0r", // .$..P.nx...|..y'..y....sf...-.....X"..)6.%.$e...rr{.X$.G..1I.q..&..+
        "zLSgtdtQhW542rS7e3wb130v+DtnZkiJwMw5A4CSbZHA4EHRsURiAJKSHyIJkJLTJpYIUnZye7eRKDlNt2kTk5Tt9HEbM+22", // ....P.nx..{|..}/.;gfH...9...m...A.Db...."....&..Rvr{..(9M.i.....q.3..
        "5Zki5dtQhW542rS7e3QbZ3YneL+qAkkRqPq+AviQLQEoAKRoWyRQAEmxbUkEQMp2um2JoOQk00lbBO3sye5O2gYpdXfmZNJm", // ."..P.nx..{t.gv'x...I.......-.(..h[$P.I.mI.@.v.m...$.I[.....N..)uw.d.f
        "y14C5ttQhW542rS7fXgb133n+ztnBiQlYOacAUDSsUhgAJCibYnAAKCkJBZJgJSd1i8iSDnZthtLlJxsXxOTkpPevZs2TNvd", // .^...P.nx..}x..}..;g.$%`..@.H`...m.....$.I..../"H9..K..l_......6L..
        "f7yOWttQhW542rS7C3wb13kn+p0zA1AiME+AlGORmAFASoktAgOCFFNbIgekZG8bSwQpO72320gUlTbt77Y2RSn2btvETHvb", // ...Z.P.nx...|..y'..3.P"0O..c...@J.-....S["..do.K.);...H..6..6E).n..L{.
        "UrQKedtQhW542rS8C3wb13kn+p15kBKBmXMGAEk/RGAAkKKTiMQAoMQ4togHJTubhwhSctM2cUTKTrvbNhEp2Unb+9uYTm9v", // R..y.P.nx...|..y'..y....s..I?D`.........8...%;...Rr.6qD.N..6.).I...Noo
        "e5mIKdtQhW542rS8f3Qb13Uuus8ZgJQIzJwzA5CULRGYAUBRsUViAJBSEosESEpOcm1JIKm0tz9kUXKy8vraWqRkJ/0VW277", // {..).P.nx...t..u........3...-...@Q.Eb..R...HJNrmI ...?dQr....Z.d'..[n.
        "KFmNaNtQhW542rS8e3Qb133v+9vzICUCM3vPABQdiwQGACnalkgMQEpMbIkASdluGpsEKSfpw7YoOe15JLFIyo572samk9XT", // (Y.h.P.nx..{t..}.... %.3{........).H.@JLl..I.n...)'..(9.y$.H.{.....
        "nLsB1NtQhW542rS7C3wbx33v+59dLCkRuzuzC1BMbJJYPCg6skQsAErMwyIBkLbzsgSSdnLacyJRctImfcQU5Ud72sRKez5t", // .....P.nx...|..}...],)..;..PLl.X<(:.D,.J.."......vr.s"Qr.&}...G{..J{>m
        "sbOF99tQhW542rS7DXQb13Uuus8ZDCkRmDlnBiDlWCIw+KFUxyIxAEgpiS0SICWnN7FFkJLT++5tLFJO/xubpBT7tr2t6fa+", // .....P.nx...t..u.....)..9g. .X"0..T."1.H).-. %.7.E.....m,RN............
        "mJ4Hp9tQhW542rS7C3Qb13ku+u8ZDCmRmNl7BqCYxCIwA4BkbEvEk2IeFgmClN2cOhZIyklvb2OTlNN3Kz7kuF1Ja+W0t7dJ", // .....P.nx...t..y.....)...{...."0..dlK.b......:.H.Iooc...w+>.]Ik..I
        "tlknpNtQhW542rS8C3gb130n+j8zGFIiMHPODPiwYxIYPCjGlkgMAEpMbIkESMpOa1sESaXJtolFSUnT7jYxSdnx7e3WZpL9", // .Y'..P.nx...x..}'.?3.R"0s....c..<(.H..JLl..H.Nk[.I...EII..61I.....f..
        "ArurGNtQhW542rS7C3gc13UmeG5VF0Cyu+reqgYISyTQVdUNIpZE9BOEY4tEP0Aq8UgiHpQ9s3FMAFQeM04sgKSkZPb7Ytq7", // .....P.nx...x..u&xnU.@......K$.U..".D...c.D?@*.H"..=.qL.T.3N,...d..b.
        "L7MvO9tQhW542rS8DXgb13ku+J35ISUCM+fMABQdiwQGACm6lkgMAEpqbEkASMnubWIRpOSkt20sSmrapj8xSdnxtvc2ZrK3", // /./;.P.nx...x..y....!%.3.........)..H..JjlI.H..mb...m,Jj.?1I...6f..
        "Bp6ta9tQhW542rS7C3gb53km+v0zGFIiMPP/MwBFpxaJmQFItYlFDgBS7MUWcaHktrmIFznp2ZzEEpWetNubKNnxdrtp1e62", // ...k.P.nx...x..y&..3.R"0..3.E.....H..E..R...q....9........(..v.i..
        "GksHfdtQhW542rS7f3Qbx30v+p1ZgKRI7M7sghRtiwQWACnZFkksQFJybZEESTluE1sEKSfNTWKLkp3ktHm1ScpO2tvGZtr0", // .K.}.P.nx...t..}/..Y..H....m....)..I,@Rrm..I9n.[.)'.Mb....y.I.N...f..
        "rqmLwdtQhW542rS8C3gb13UuuvYMhpREzOw9A5CMbZGYGYCkE1siXiSbNBLxoKQ0rS0+5OS7bROTVNKerzlJJEqy0/Y0Vdu0", // .....P.nx...x..u......D..=...m......["^$.4..4.->..m..T..9I$J...4U.
        "g6EP4ttQhW542sy8DXgb530n+H/ng6RIzLzvAKBoWyQwA5BiEovEACDF2LJIgKTspIlFkHKSdhtblJR0t91tTVJyfb02a7a9", // .....P.nx...x..}'...H....h[$0..b.... ..H...E.r.v.[..t..mMRr}.6k..
        "qoyNsttQhW542rS7C3wb13kn+p15gBSBmXNmAJKJTQIzACnGtkgMQFJqbYsAScluG0sESSfZtIlFSsn2dtPGpCTH26fltrvb", // .....P.nx...|..y'..y....sf...M.3.).H.@Rjm..I.n.K.I'..EJ..v..$....
        "hEutsdtQhW542rS7fXgbx3kv+s4ull/A7swuQNGxRGAXIMXEFokFSImpJZEAKdlOE5EgpTRJE0uknH7dpBYpOemHm5h272l7", // .K...P.nx..}x..y/...._....@.D`. .....H..%..).N.. .4I.K..~..)9..v.i{
        "MKkhDdtQhW542rS7C3wb13kn+p0zM6REYOacGYCiHyIwAEipjSViAJBiNrFIAJTs2zQRQUpputttRMrJ9t4+YpJy7F+33Ubp", // 0.!..P.nx...|..y'..33.D`....."0.H..%b..b6.H....4.AJi..mD....>b.r._..F.
        "HaGlLttQhW542rS8C3gb53nn+34zGFISMfN9MwAlJxaBmQEpJrFFDi4Uk9iScKHktKklXuz0JJvEJOWk52TTWKRku+3mbNS0", // .....P.nx...x..y..~3.R.1.}3.%'....)&.E.....p..%^..$..$..d.X.d...l.
        "NIwnfttQhW542ry8C3Qb13ku+u89GFIiMLP3DEAxtkRgAJBiYlvEACDFxLFIEKTttLZFkJST04ctknba3jSJSUlObm9PYiV9", // 4.'~.P.nx...t..y...=.R"0...@1.D`..bb[.. ..H.....E....-.v..4.IINnoOb%}
        "fp9bcdtQhW542rS7fXgb13kn+p4ZDEkRmDlnBiDp2CIw+KAYxyIwAEgptiUSJCW7N5FEkJLr5sMSJTn9uG0tklLibnYbM2nv", // ~.[q.P.nx..}x..y'....I..9g. .."0...."0.H).%.$%.7.D......%9..m-.R.nv.3i.
        "yn3XzdtQhW542rS8C3gb130n+j8zGFISMXPODEAxD4s4MwDFpraIAUCKaRKLAEhZfSXiQ47TNo1Jymmb3ZsNSUlWtq+o7ddt", // .}...P.nx...x..}'.?3.R.1s..@1..83.....@.i...HY}%.C..6.I.i...IIV.....m
        "53VT7ttQhW542rS8C3wbx3UvfGYXS1AEdmd2wYdtkcACoEQ/RGIBklJaiyRISnYa2yJIKvVt01iknDT92iQmJTlu0zamb297", // .uS..P.nx...|..u/|f.KP.vgv..m....D?Db..RZ.$HJv.."H*.m.X..4..$&%9n.6.oo{
        "zljRvttQhW542rS8C3wb133n+z8zGFIiMXPODEAysU1iZgCSTiKReJFs4kjEg3KSJrFIUE6fiUnKbfa220YU5fh2+4j6yE2a", // .X..P.nx...|..}..?3.R"1s..@2.Mbf..N".x.l.H.r.&.HPN..I.m...F...v....M.
        "4J/xvdtQhW542rS8fXgb133v+TtnMKREYOacGYCibZHADABKcSQSA5CUYlsiAVJ22toWQcpJ0zaWKCl9u7exSUpO2iaN6b7c", // ....P.nx..}x..}..;g0.D`....m....Jq$....b[".Rv...A.I.6.()}...IJN.&...
        "VH19AdtQhW542rS8C3wb13kn+p0zACgRmDlnBiCZRCIwAEjRsS1yAJBimlgiAFJ2tklMkJSa21dEyunr9qYmKdnem9wmSh/b", // T}}..P.nx...|..y'..3.(..9g. .D"0.H.-r..b.X".Rv.IL....WD.....&)...&J..
        "eXX5IttQhW542rS8C3wb13kn+p15kBSBmXNmAIqORQKDB8XEFokBQIpJLJHgQ3bbxOJDTpNsG4mS06bpphYlq017u43pbHNv", // yu.".P.nx...|..y'..y....sf...E........@.I,..Cv...CN.l......%.M{...lso
        "UFh7cttQhW542rS8D3Qb133n+7szGFISMHPvDEDRsUViZgCKaWwRgz8Um9iW8IeSum1skaCdbPuamKTcPd3dbixSst1suy/a", // PX{r.P.nx...t..}...3.R.0s..@.Ebf..il..?.......ml...l.....=..n,R..l./.
        "A5h+M9tQhW542rS8e3gb13nu+601A5AiMLPWDEDRtkjMACDF2BaJAUhKvogkQEl2LjYJSk6z2yQSJTc5u7snFik5yellR3S6", // ..~3.P.nx..{x..y...5.."0...@.H.. .....HJ..$@Iv.6.JN..$.%79..'.)9..eGt.
        "t3ryj9tQhW542rS8C3gb13UuuvYMhqRIzOw9A1B0bBGYAUAxiU3iSbKJLREP2k6b2OJDTtrmxCal5OSc9ItNUrLV3p4mTNvz", // .z..P.nx...x..u......H..=.Ptl...@1.M.I..-...N...CN...&....MR...&L..
        "mnJ2rNtQhW542rS8DXgb13km+p35IUUCM+fMABRtSwQGACkmtkgMAFJ0bIkEQEpOE1sEKSdtk9qi5La77d7EJGXHt91tw2z3", // .rv..P.nx...x..y&...!E.3....mK...)&.H..Rtl..@JN.[.)'m......$e..m.l.
        "s1/0/NtQhW542rS8C3wb13kn+p0ZDCkRmJkzA1CMY5GYGYBkElvE4EEybWwRACm7+2tik6DcdpvGpiinu91ta4qU422398Zt", // ._...P.nx...|..y'....)...3.P.c....d.[..A2ml..)..kb...v..(...mk...m...m
        "nZjU/9tQhW542rS7e3Qb13kv+u09M3xiZu8BQNKWSGAAkKJjicQApMQ4lgiAlOPUtkhQstPbNpYgOUnb0zYiKSe+6SOic9t1", // .....P.nx..{t..y/..=3|bf..@.H`...c.....8......HP...6. 9I..6")'..#.s.u
        "KXpYQ9tQhW542rS8DXwb13Uneu4MhpQIzNw7A5B0bJGYGYBkElvkACDFJI5EAKSsfiQWSSlx23yYlJKm7UsaipKsbTevVdrX", // )zXC.P.nx...|..u'z.......;..tl....d.[.. .$.D...~$.I)q.|.....K....m7.U..
        "BHLcYNtQhW542rS7C3wb133n+z/z4BMz58wAFG2JBAYPio4tAgOQspJYIsCH7DwsEaTstOkmEuU8+tl2E5GSk/Sx12LSTdOX", // .r.`.P.nx...|..}..?...3....m......-.....X"...<,....&..<..v.......b.M.
        "LV9eMNtQhW542rS7C3Qb933n+/vPYEiJxMz/PzOgmEQSMTMASce2SLxI5mFZeFBy2yQWH3K6aXtikXKb0+1tI5Gy3Tb3bJR2", // -_^0.P.nx...t..}....`H....?3..D.13.I.H.H.aYxPr.$..r.i{b.r...m#...6.l.v
        "hJER9dtQhW542rS7D3gTV373+ztnZiRja+ackWQcApZGksHJgq2RbCCbgC0bSNJmwbJJtm/bTTAkb/t2211sk91t73s3cfr0", // .....P.nx...x.W~..;gf$ck.d...F.....l ..-.H.f..I.o.M0$o.v.]l..m.{7q..
        "MHOdSdtQhW542rS8C3gb130n+j8zGFISMHPODEDKtUVgBgDJPCxiAJBimlgiQEpW0iQWSMl5tbVJyUmzd/fGpCRbu93eRr19", // 0s.I.P.nx...x..}'.?3.R.0s..@.E`...<,b..b.X"@JV.$.H.y..I.I.w..$[...F.}
        "HXsZattQhW542rS7DXgb13km+p0zM6REYOacAUDRtkRgBiBFxxaBAUhJiS2RICjbaWKLIGWn26axKClNd9vrmKRku91tEqbd", // .{.j.P.nx...x..y&..33.D`..@.D`. E....HI.-. (.ib. e...()Mw..d..m...
        "NFabOttQhW542rS7C3gb130n+j/zICUCM+fMAJScSARmAFBMYpMYAKQU25IIgpTTRyyCpJO03dYipcTtd3sbk5Qc3203MbN9", // 4V.:.P.nx...x..}'.?. %.3.....H.f.PLb..........G,......"...w{.....m71.}
        "GpG7OdtQhW542rS8C3gb53km+v3/zJAUgZn/nwFI2pYIDABStGOJGACklItFAqRkt00sgZRcZ5uNRcppm3Y3MUnJcdP2rNme", // ...9.P.nx...x..y&..........H....R.c......E..d.M,..\g..E.i.v71I.q....
        "rnM3hdtQhW542rS7C3gb130n+j9nZkCJwMw5A4CibZHA4EExsURgAJBSYpsESEq2t7FIkHKy220sUXaa7va2EUVZzfb2tmaf", // .s7..P.nx...x..}'.?gf@...9...m...A1.D`..Rb..HJ...H.r..m,Qv.....EY....f.
        "g3uzpttQhW542rS7DXQb13nn/dyZASkSmLl3AJB0LBIYAKToRCIxACixjS0SACW7m8QiSDlfzYlFyum229OtScmJT5tswzbd", // .{...P.nx...t..y....)...w..t,.....D"1.(..-..%..."H9_.E....I.O.l.6.
        "qlYx9ttQhW542rS7C3Qb13ku+u8ZDCiRmCdAybZEYGYASo4tEYMHxTaWSBCgbLeOxJfSe3qTWBSVplmnJzFF2XFfaej0tCen", // .V1..P.nx...t..y.....(..'@.D`f.J.-....6.H..l....{z.X...Y.'1E.q_i...'.
        "+ZY0t9tQhW542sy7C3gb130n+j9nBqREYOacGYCibZHAAODDiUhiAJCiHyIJkpKdhyWClN3c7cYWJSft3W03ImUnadpNzWz3", // ..4..P.nx...x..}'.?g..D`....m.....Hb....".....%.......%'..m7"e'i.M.l.
        "TXS4C9tQhW542rS8C3gb15XneW49SIlA1b1VAEnbEolCgRSdWCIKD5JJbJEASNnZpG2BlJz09iQWJTuZ3u48SEpOOjPTMfs1", // Mt...P.nx...x...yn=H.@.U.I...B...X"...Il..H..m.....$.%;...<HJN:3.1.5
        "YHw8KNtQhW542rS7C3wb130m+j9nBuADM3PODEDJtkRgAJCiY5HAACAlJ5YIgJTtpLVEkLKz3aaxSDnp494mJiW7z61N56a9", // `|<(.P.nx...|..}&.?g...3s..@.D`...c... %'.......D.....H9...&&%..M.
        "SVG+eNtQhW542sy7DXgb13km+p0ZDCmRmDlnBoDoWCIwA4CkE0vEACDFJLZEgKSctoklkLTT7baJSMr93W3DHzlu924bJt3t", // IQ.x.P.nx...x..y&....)..9g...X"0....K.. .$.D.....%......H...m..9n.n.&..
        "Z5aee9tQhW542rS7C3Qb13ku+u89Az4EzOw9A1C0JREYAKRoWyQwAEkprSQSIGXnYUsEKTv39LaRKLmP29smpqQkPultLKld", // g..{.P.nx...t..y...=.>...=.P.%....h[$0.I).$. e.aK.);....(....&..$>.m,.]
        "03QSx9tQhW542rS8DXgb13km+p0ZDCmRmDlnBiCZxCYw+KHUxhYxAEipdSwRACk72dYRSMpNbrOJSMlJ++ztTURSsm7bbavd", // .t...P.nx...x..y&....)..9g. ..&0.....1.H.u,..);...H.Mn..H.I...MDR.n.m..
        "/nyW5NtQhW542rS8e3Qb133v+9szA1Ai57FnAIp2RAKDByXHkoABQIqJLREASdttYokgKSe3TWNSsrPSp01KdnJ61m3CtD1t", // .|...P.nx..{t..}...3.P".g..vD...%...@..-..I.mb. )'.McR...MJvrz.m.=m
        "11EUtNtQhW542rS8DXQb15UmeF8VQEokqt6rAig5lghUFUAxTiSi8EMpaVsiAFJ2koktkFT6Z6dtkZIzJ5nexCTlTLq3pztK", // .Q...P.nx...t..&x_.@J$...(9..T.@1N$..C)i[".Rv..-.T.g.m..3'...$.L...;J
        "y4S+ottQhW542rS7C3gb130n+j9nMCRFzsw5MwBF2xIxA4CU7EgEBnxIdiQRACnbSWyRIOWk26aRKDm322YTi5Rsp+3eRnT2", // ....P.nx...x..}'.?g0$E..93.E..1....H..|Hv$..).Il. ...(9..f...l...Ft.
        "f2YyHttQhW542rS8DXgb13km+p0ZDEkJmDlnBiAZWxIxA4CiW0vk4IdUk9gifiglbWIJJOX+3toilaTtbjchKTne3u5N1J/d", // .f2..P.nx...x..y&....I..9g. .[.1...[K...T.."~(%mb.$...."...n7!)9...M..
        "Um62PdtQhW542rS8D3wb13Umeu4MhqRIzNw7A5B0IpGYAUDRsUViAJBiE1skQNJWNrUlkFSSbppYpOyXvP62jflHttP0T5h9", // Rn.=.P.nx...|..u&z....H..;..t"...@.Eb..b.[$@.V6.%.T.n.X......G...O.}
        "e0M0bdtQhW542rS8C3Qb933n+/vPYEiKwMz8ZwCKdiwS/xmAYhJb5OBBMb61RDwoOY/a4kNOT7pNTFJK0912W5GS7d3taaOc", // {C4m.P.nx...t..}....`H....g..v,....b.[..A1..D<(9...CNO.MLRJ..v[.....i..
        "VYQUbttQhW542rS8DXgbx3ku+s3+EBSB3ZldgKJtkcACIEXHEokFSElOJJEgKdlNIpKgZCen+ZFIJb39iy1ScuKn7alFJzk9", // U..n.P.nx...x..y........]..m... E....HIN$. ).M"..d'...H%...-Rr...E'9=
        "4WaY0ttQhW542rS7D3wb13Umeu4MhpRIzNw7A5B0bJGYAUgxsS1iAJBiYlsiAFJy28QWSMpJ09YxSTnt5vXtmqJke5OmDdNt", // .f...P.nx...|..u&z....H..;..tl...H1.-b..bb[".Rr...H.I..1I9....d{....m
        "zG4c8dtQhW542rS8C3wb13kn+p0ZDEmRmDlnBqDoRCIxA4CiE1vkACDFprVEEKTkdG9sgpSd9HFjk1K6abeNzYdsd9vdRtnt", // .n...P.nx...|..y'....I..9g...D"1....[.. ..D...tol....qc.R.i...lw..F..
        "5UOeodtQhW542rS7C3Qb933n+/vPYEBJxMz8ZwCSiWMS8wDFNrZIvEimSSziRSVNa5sEZWdvm8YSZWe33U0jkZJ1t/ckVra9", // .C...P.nx...t..}....`@I...g...c....6.H.H.I,.E%Mk..ego...eg..M#..u..$V..
        "PYsgZttQhW542rS7fXgbx3kv+s7sgqQI7M4sAIqORWIXACk5tkgsSEpyLJEASMpOmlgEKTvpaWuJktP09MsiJbtJb08tOm1v", // =. f.P.nx..}x..y/......,...Eb..)9.H,HJr,..H.N.X.);.ik......"%.IoO-:mo
        "iWms2ttQhW542rS7DXAb130v+j9nd0GJ2I+zACj6QwR2AVJMY5FYgKSYxpYIkJLdprEFkHbSr9iklPTdmdvWJGXH0/beRL3t", // .i...P.nx...p..}/.?gwA....(.C.v.RLc.X...........v.......$e....D..
        "pGEo+dtQhW542rS7DXgb13km+p0zMyBFYOacGYCSbYnAACClxBKJAUCKqW2RACnJaWKLIOVk001iUVLcbbebmKTkJO1tY6a3", // .a(..P.nx...x..y&..33 E`....m... .....@..m..).ib. .d.MbQR.m.....$.mc..
        "jUyqqdtQhW542rS8DXQb130v+L8zGJIiMHPvDEDRsURgBgDFxLaIwQfFJLZIgKTstIklfshJX5pEFJXm7Xt9z+GH7bSv3Vp5", // .L...P.nx...t..}/..3.."0s..@.D`........$.H...%~.I_.D....{}......Zy
        "o4uKqttQhW542rS7f3Qbx30v+p1dLCkR2JlZABRtSwAWPyTalggsQEpKLIkAScluY4sEJafpa2KJktPmtbexQMl2Tn9FdPJ6", // .....P.nx...t..}/..],)..Y..mK..?$..,@JJ,..I.nc..%..kb.....@.vN.Et.z
        "F2kGFttQhW542rS7DXgb13km+p0ZDCmRmDlnBqDoRCIwGICiE0vE4Idi21gifii5P7EFknbabZuYlJPs9tmmJinZ3rbbRmn3", // .i...P.nx...x..y&....)..9g...D"0....K...b.X"~(.?...v.m.......&)...Fi.
        "OmGCNdtQhW542rS7fXgbx3kv+s4ulpQI7M7sAhRdSyR2F6CYxBK5+KCYxJIIgJLd5kMCKdtp74ljSkqTntvTmKTkuB+3tdLT", // :a.5.P.nx..}x..y/...........]K$v...............C.).i.cJJ...........
        "E0wAZdtQhW542rS7C3Qb13ku+u+ZASgJmNl7BiDp2CIwM+CjjUVi8KCYxJIIgJTdRySBpJ2e3DYWKaVJe3oTU5Qc33O6Giu9", // .L.e.P.nx...t..y....(...{. .."03.Eb......G$.....6.).I{z.S...s..+.
        "QIwFJNtQhW542rS7D3Qb13kv+N07A4AiMHPvDEDRsUhgAJBSYonAACSlOJZIgKTsNLFEkFLy2tfaoqQ02bYnEUQ5zXvtxqLT", // @..$.P.nx...t..y/..;.."0s..@.H`..Rb...$.8.H...4.D.R.....4.'.D9.{...
        "9G6JmNtQhW542rS8C3gb13UuuvYMhhQJzOw9A1C0LREYAKTo2CIxAEgxiSUSACk7t4lFkJSTvmKRtNPePmKTlBy3PactfW9f", // .n...P.nx...x..u.........=.P.-......"1.H1.%..);..E....b....>b....=.-}o_
        "2WYNu9tQhW542rS8DXQb13Uuus+ZGVAiMDNnBqAU2yIwAEjJcUxiAJBSakvkgKTs/NgiSClp82OLlN2kt3c1Iiknad+9L2Ha", // .f...P.nx...t..u....P"03g...."0.H.qLb..RjK...."H)i.c....w5")'i./a.
        "8EuP69tQhW542rS7D3Qb133v+bszGFIiMHPvDEDRjkRgZgCKsS0SA4AU88ciAZKy05daBCml2f6zSDnNe0mamKTkuN2+xmxO", // .K...P.nx...t..}...3.R"0s..@.D`f...-......"....Z.)....H9.{I......lN
        "3oyv6NtQhW542rS8f3wb13Uneu7MgJQIzNw7A1B0LBGYAUgxtkViAFBSWkvED0p2m9giSDntvo1tQVLS7GsTm6ScpP10Y9HZ", // ....P.nx...|..u'z......;.Pt,...H1.Eb.PRZK..Jv.."H9...mAR..k......tc..
        "am4jVNtQhW542rS7C3wb13kn+p0zgyFFYOacGYCiY4vAACAlOxaBAUhKWVsiAFKy2yQiQcrppkktUZK37d02MSnZyd1t1mba", // jn#T.P.nx...|..y'..3.!E`....c... %;...HJY[".R..$"A..I-Q....61)...m.f.
        "R2and9tQhW542rS7DXgb13km+p0zM6BEYOacGYCiLJHAACDF2BKJAUFZrS0SACklaWOJ0I+bTZtIoJzNtpvGJiUn2XbbmEnb", // Gf.w.P.nx...x..y&..33.D`....,... .....AY.-..)%ic...M.H.....&%'.v.I.
        "bkslJ9tQhW542rS7DXgb13ku+J0ZDEkRmDlnBiDpWCIw+KEY2yIxACgxiS0SBCn5polFkFKaX1ug7OR2u3trkpLj7V+i9rZp", // nK%'.P.nx...x..y.....I..9g. .X"0...."1.(1.-..)...E.R._[...v.{k...._...i
        "x4Vq4ttQhW542rS7fXwbx3UufGZ2QVIEdmd2AYq2RAILgJQciwQWBGXZlkiApJQv2yRIOR9tYomy0+a2t45Iyk76kcRM2nvb", // .j..P.nx..}|..u.|fvAR.vgv...D.........e.H.../.$H9.mb.....H.N...L.{.
        "c2fmXttQhW542rS7DXgb13km+p35ISUCM+fMACTjSAQGACklsUgMAFLsOhYJkJSVZmMRpOx0k00sUs7P7e3emJRkp+n2Nky3", // sg.^.P.nx...x..y&...!%.3...$.H...)%.H..R.:.....fc...t.M,R......d...6L.
        "Xm9ifdtQhW542rS7C3wb13kn+p15kBSBmTMDgKItkZgBQEq2RQIDkBQTWyIHpGQ3aSyCpJJuml9MUrZzs20Sk5Tc9G7TmGl2", // ^ob}.P.nx...|..y'..y....3...-...@J.E.....["..d7i,...n._LR.s.m.....n.iv
        "d0LgLdtQhW542rS7C3wb13kn+p15kJKAmTkDgGRiW8DMACSziUUMHiRzk1jEg7K6bWPzITdptolFyk3bbbeRRMm5e/Nr673b", // wB.-.P.nx...|..y'..y....9..db[...$..E..$s.X...mc.!7i..E.M.m..D.{.k..
        "WYXALttQhW542rS7fXwb13km+p75ICkCM+fMABRtSwQGHxRtWSQGICn5QyIBUrKTJhJByk62SWxBkrPbdJOYpOym2SYx023v", // Y....P.nx..}|..y&... ).3....mK....mY$. ).C".R..&.A.N.IlA...t.....&1.m.
        "7WdMkttQhW542rS7C3gb13km/J25kBKJmXNmAIqKRQIDgBR9kYABQEpOLJEAKdlNa4kg5Wyam0VJSbfpxaYkJ+mmm5pJum3/", // .gL..P.nx...x..y&.......sf...E....}...@JN,..).Mk. .l..EII...$'..I.m.
        "wG/IsdtQhW542rS8DXgb13km+p35ISkCM+cMAEq2RQADgBRtiwQGICW5kUgAJG03jSWClNJ2N7FJyslm291aJOX8dHcT09vt", // .o..P.nx...x..y&...!).3...J.E....m... %..H.$m7.%...v7.I..f..Z$..tw....
        "6UJK4dtQhW542rS8DXQb130n+r8zGJIiMXPvDEDRsUVgBuBHbInEACClxJaEAUnZaWuLIKX4dNONRclOu+81G5GS89Hdpmba", // .BJ..P.nx...t..}'..3.."1s..@.E`..Gl... ....I.ik. ..t.E.N..5......f.
        "uoJPoNtQhW542rS7fXgb133n+zvzQlIEZs4ZACQdiQBmAFCyLREYgJTU2BIBkpKdppYIUnZuu60lSkpuu30am5TkuO22EdN0", // ..O..P.nx..}x..}..;.BR.f...$...f.P.-..............Rvn..%JJn.}........t
        "DmDDHNtQhW542rS7D3gb13Uneu4dDEmRmLl3BqBoxyIwAEgxiS1iAJBiE1siAFJW28QSSMlJu00sUkqy22wb84//tPvamt3u", // .`...P.nx...x..u'z...I...w..h."0.H1.-b..b.[".RV...H.I.M,RJ..l........
        "I2hHP9tQhW542rS7D3wb130n+Hvzh6AIzLw3A1C0LRKYAUgxsURiAJJiEkskCMpxr7FEkJLd9hJLlOxk9/Yam6TsuO12aznX", // #hG?.P.nx...|..}'.{...7.P.-...H1.Db..b.K$..q..D.....K..d.......vk9.
        "CkXFb9tQhW542sy7C3Qb530n+v9mMCBFYOb7ZgCKdiwSMwNQTGJLGDwoJo0l4kHZbZNYICmn3baJSclpmzaNJcqPdrdJtO2m", // .E.o.P.nx...t..}'..f0 E`..f..v,.3.PLbK.<(&.%.A.m.X )...I.i.6.%.v.I...
        "JILlbNtQhW542rS7e3gb13UvuvY8SIrEzN4zAEXHIoEBQIq2JRIDkJIcSyJAUJadxBJBykl70lii5DS9bRKLpPJoTxubdtrT", // $..l.P.nx..{x..u/..<H....3.E."..@..%.....K"@P....A.I{.X..4.m....hO..v..
        "kGBp0NtQhW542rS7DXgb13km+p0ZDCmRmDlnBqCY2CYxA4Bk29ji4Idik8Yifij5bhvbBCk33ae3MUklbbfdbkRKsm5v90fP", // .`i..P.nx...x..y&....)..9g....&1..d.....b.."~(.n...)7..1I%m..nDJ.no.G.
        "vWjt89tQhW542rS5DXQb130n+r93MCRFYObeGYCSbYnAACDFxBKJAUBKSWSRICnZaWKJIOWmr11HomTntd1tI5Jy4mRfUzNt", // .h...P.nx...t..}'..w0$E`.....m... .....@JId. ).ib. .]G.d..m#.r.d_S3m
        "lEVvo9tQhW542rS6C3Qb530n+v9mAJImMTPfDEAqjkVgHiCZ2BY5GIBkciOJeJBy2yQWH0ras01jknLb3TaJSUqOt+3dRtk9", // .Eo..P.nx...t..}'..f..&13..@*.E`. ...9..dr#.x.r.$..J.Mc.r..6.IJ....F.=
        "iJDFtdtQhW542rS7e3Qb13kv+u09A5AiMLP3DEAxtkRgBiDFxBKJAR+S41gkQMp20loiSDnpam8sUbL7OE0Tk5TjpI/ETNNH", // ....P.nx..{t..y/..=.."0...@1.D`. ........X$@.v.Z"H9.jo,Q..8M.....L.G
        "PHJJCdtQhW542sy7C3Qb530v+P9mMCRFYOb7ZgCKji0SMwAoOrZEDABSdGObBEBK3rax+JKTPbltRFLp9mabdUhKtnv37iZK", // <rI..P.nx...t..}/..f0$E`..f...-.3.(:.D..Rtc..@J.....=.mDR..f.uHJ.{..&J
        "EXrNKttQhW542rS6D3zb1n0v+jsAIckigXMAUlYaWyJAUnab2CJISnabJhYpyem/xCYlp317WxNJbrvdbW0l2Wm6dWu03fu2", // .z.*.P.nx...|..}/.;.!.".s.RV.["@Rv.."HJv.&.)...&%.}{[.In..mm%.i.uk....
        "OFdPettQhW542rS7C3Tc1nnv+21gQFKcAfYGMBRjW+QAmKEYxxaJmeGjSSxxHpTc5mHxISe35+TYIpWkt7dtLJKyfXr7Uh9Z", // 8WOz.P.nx...t..y..m`@R....0.c[..........I,q....a.!'...."....m,..}z.R.Y
        "FpBvedtQhW542rS7C3wbx3kv+s3sLkkR2J3ZBSnJlggsAFL0QwQWACU5lkiCpBQnsUSClNPm/BJLlOy0adNaJO28ThOLTk+f", // ..oy.P.nx...|..y/....I....)..,.R.C...%9.H...'.D......K..i.Z$..N..NO.
        "onLjxdtQhW542sy8C3Qb130n/L8zGFAiMXPvDEDRiUViBgBFPyTiRYpuYokAKFlJE0sgqbjPWKTkJN10m4qkbLdfdxN1d9um", // .r...P.nx...t..}'..3.P"1s..@.Eb..E?$.E.nb..(YI.K ...X..$.t...l._w.uw.
        "j3pn5ttQhW542rS7fXwb13nv+ZwZDCmJmDlnBiCZWBIxMwDJvEjE4IVSsrZEvFB22sQWX+S+3TQmKadp97Y1Scl20u5t1Jfd", // .zg..P.nx..}|..y.....)..9g. .X.13..H...R..D.Pv..._..4&).i..5I.v..m..
        "plfltttQhW542rS7C3Qb13ku+u8ZDEmJmNl7BqDo2CIxA4CiE5vEACBFJ7FJPCQnbRIJJOWmaZqYpJz0dRrzIcc9bdPIfZ2m", // .W..P.nx...t..y.....I...{...."1....... E'.I<$'m..$.i.....u..!.=m..}..
        "WFZBJdtQhW542rS7C3gb13nn/Z4zMyRFYOacGYCibZHA4EIxsUViAJKSLxIJkpKdppZ4kd1tNrVE2knbbWIbpORke7PpXtPG", // XVA%.P.nx...x..y...33$E`....m...B1.Eb.../.......x..m6.D.I.mb...d{..^..
        "7LTNmdtQhW542sy7C3wb13kn+p0zM4REYOacAUDRsUVg8KCY2CIxACmpqSUSBCk7u40lkHTSpy1Kdrvb7bYmKdnp69bMpps+", // ...P.nx...|..y'..33.D`..@.E`.."1.)..%..);..%.t.-Jv....&)......>
        "wbxJuttQhW542rS7C3wb133v+T/zICkCM+fMABQdiwQGACnalkgMAFJKYokEQMlum1gESSe5vW0kSk76yG1tkrKTvq20vXfT", // ..I..P.nx...|..}..?. ).3.........).H..RJb..@.n.X.I'..m$JN..mm.......w.
        "6JHL6ttQhW542rS7C3Qc13km+N+qLoAEuureqm4QegFdjwbhh8iurm4Qnlgi+wFQcWyZQIOKZ5IdmwSlvHYcEyBlbXZmEmaS", // ....P.nx...t..y&........n.z.].....n..X"..Pql.@..g......v.. emvf.f.
        "xlbr6dtQhW542rS7f3gb13nn+54zM6REYuacGYCiY5HAACBFJxKJAUhJjm0RIClZ6SYSQcpObtLYguS0vbutI5Ky43Zva9G5", // .V...P.nx...x..y...33.Db....c... E'...HI.m. )Y.&.A.Nn.....#...vok.
        "crRnVdtQhW542rS8C3wb13kn+p0ZDCmJmDlnBiDphwjMDEAxdSziRYpJbIsASFnNywJJJe5v29ik5Dbd7DbmQ7J6u7uJmtt2", // r.gU.P.nx...|..y'....)..9g. ....@1u,.E.Il..HY...I%.o...6..6.C.z.....v
        "X7zjdttQhW542rS7DXgbx3ku+s3sLkgR2J1ZACRtiwQWACnZlkgsQFJ0YpEEQMlumlgEKTttT2OJktPk9jaNKcp2zj19GtP9", // _..v.P.nx...x..y.....H..Y.$m....).H,@Rtb..@.n.X.);mOc.....6.).v.=}...
        "dpFhJttQhW542rS7D3wb130n+HszGFIiMPPeDEDStkRgBiBFxxaJAUFKSWyRACjL+WcRJJX02o0lUnGT7W4TkZQTb/eyCZNr", // v.a&.P.nx...|..}'.{3.R"0...@.D`. E....AJIl..(..g.$...%Rq..n....o....k
        "JVFkZ9tQhW542rS7C3wb13kn+p0zA5IiMHPODEDRlkjM4EHKsURiAFKiY5skQMp22tgiKNlpb9JIpOxtm7SxSMluNptNTLfZ", // %Qdg.P.nx...|..y'..3.."0s..@.H..A.Db.R.c.$@.v.."(.io.H..m...H.n6.ML..
        "kbPo29tQhW542sy8DXQb13km/N75ASkCM3cGAKU4FoEZgBTrSCIGACk2iUUCIGW12VgEKbvpl9YRKbk/+7WNScqJd89pazlf", // .....P.nx...t..y&....).3w...8......H"..)6.E. e..X.)....).?...I.w.ik9_
        "vLts+NtQhW542rS7C3wb13kn+p0ZDCmRmDlnBqDoxBIxMwAlx7ZIvCgltSyCAKW0TSzxobS7aWOLtNNtNt1alOQ63W5itXtv", // ..l..P.nx...|..y'....)..9g.....13.%.H.(%.,....M,.ic...m6.Z..:.nb.{o
        "lZbuqNtQhW542rS7DXgb13nn+54zGJIiMHPODEAytkVgMADJOJaIAUCKaWKR4IfkbBOLIOV8dLOxSNlpu2k3Jik53nTbWGm6", // ....P.nx...x..y...3.."0s..@2.E`0..8...@.ib....l.. .|t..H.i.i7&)9.t.Xi.
    ];

    // Idempotent; safe to call at the top of the scenario's Run.
    public static void Seed()
    {
        foreach (var (key, value) in RsvText)
            RsvFunctions.Add(key, value);
        foreach (var (key, valueBase64) in RsvRaw)
            RsvFunctions.AddRaw(key, Convert.FromBase64String(valueBase64));
        foreach (var record in RsfRecords)
            RsfFunctions.Add(Convert.FromBase64String(record));
    }
}
