<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../AnoMech/Helpers/Utf8NameEncoder.cs" Link="Utf8NameEncoder.cs" />
    <Compile Include="../../AnoMech/Core/Game/Bgm.cs" Link="Bgm.cs" />
    <Compile Include="../../AnoMech/Pointers/DrawDataPointers.cs" Link="DrawDataPointers.cs" />
    <Compile Include="../../AnoMech/Pointers/TimelinePointers.cs" Link="TimelinePointers.cs" />
    <Compile Include="../../AnoMech/Core/Map/MapEffectResets.cs" Link="MapEffectResets.cs" />
  </ItemGroup>
</Project>
