// Generated by tools/parser.py --code. Edit freely.
// Player id -> role mapping (first-seen order inside the window):
//   1001875C  -> PartyRole.MainTank
//   10056A3A  -> PartyRole.OffTank
//   10019262  -> PartyRole.RegenHealer
//   10018A1B  -> PartyRole.ShieldHealer
//   10018BF0  -> PartyRole.MeleeDpsA
//   10018DC8  -> PartyRole.MeleeDpsB
//   100188C6  -> PartyRole.PhysRangedDps
//   1004E71C  -> PartyRole.CasterDps
// Suppressed 261|Change keys (state-sync churn — no C# emission):
//   CurrentMP, Heading, MaxHP, NPCTargetID, PCTargetID, PosX, PosY, PosZ

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Numerics;
using AnoMech.Core.Game;
using AnoMech.Core.Game.Ai;
using AnoMech.Core.Game.Party;
using AnoMech.Core.Map;
using AnoMech.Core.SimObjects;
using AnoMech.Scenarios.Umad.P2Forsaken.Ai;
using static AnoMech.Scenarios.Umad.UmadConstants;

namespace AnoMech.Scenarios.Umad.P2Forsaken;

public sealed class UmadP2ForsakenScenario : IScenario
{
    public string Name => "Forsaken";
    public IPhase Phase => UmadZone.P2;

    public void DrawSettings() => settingsWindow.Draw();
    private readonly UmadP2ForsakenSettingsWindow settingsWindow = new();

    public IReadOnlyList<IScenarioAi> AiStrats =>
    [
        new UmadP2ForsakenKroxyRinonAi(),
        new UmadP2ForsakenSouthFlexAi(),
        new UmadP2ForsakenKroxyRinonOldAi(),
        new UmadP2ForsakenSouthFlex341OldAi(),
        new UmadP2ForsakenLpduBuddiesAi(),
        new UmadP2ForsakenP3ZBuddyMeowAi(),
        new UmadP2ForsakenZP6SouthAdjustAi(),
    ];

    // NA holds the existing strats; EU holds this branch's new strats — isolated copies
    // of NA strats over their own forked helpers ("p3Z Buddy Meow" from Kroxy-Rinon 341,
    // "zP6 South adjust" from South Flex 341).

    private UmadP2ForsakenState state = null!;
    private SimWorld world = null!;
    private SimParty party = null!;
    private DamageSolver damage = null!;


    public void Run(SimWorld worldParam, int? selectedAi)
    {
        world = worldParam;
        party = worldParam.Party;
        state = new UmadP2ForsakenState(party, settingsWindow.Overrides);
        if (selectedAi is { } idx && idx >= 0 && idx < AiStrats.Count)
            ((IScenarioAi<UmadP2ForsakenState>)AiStrats[idx]).Run(state, world);
        damage = new DamageSolver(party);
        damage.SetStatuses(DamageType.Magic, StatusId.MagicVulnerabilityUp);
        
        
        Run_Kefka_40004FD3();
        Run_Kefka_40004FAC();
        Run_Kefka_40004FD0();
        Run_InstanceEvents();
        Run_OtherDebuffs();
        Run_PlayerLockons();
    }

    private void RunTower(float timeBase, Direction direction)
    {
        
        world.Events.Add(timeBase, () => world.Map.AddEffect(packetFlags: 0x00020001U, index: (byte)(direction.Index() + 1)));
        world.Events.Add(timeBase + 3f, () => world.Map.AddEffect(packetFlags: 0x00020008U, index: (byte)(direction.Index() + 1)));
    }
    
    private void Run_InstanceEvents()
    {
        
        world.Events.Add(1f, () =>
        {
            for (int i = 0; i < 8; i++)
                world.Map.AddEffect(packetFlags: 0x00000004U, index: (byte)(i + 1));
        });
        world.Events.Add(1f, () => world.Map.AddEffect(packetFlags: 0x00080004U, index: (byte)0x00));
        world.Events.Add(2.37f, () => world.Map.AddEffect(packetFlags: 0x00080004U, index: (byte)0x11));
        world.Events.Add(9.43f, () => world.Map.AddEffect(packetFlags: 0x00020001U, index: (byte)0x11));
        world.Events.Add(11.04f, () => world.Map.AddEffect(packetFlags: 0x00040001U, index: (byte)0x12));
        
        Direction d1, d2;
        (d1, d2) = state.GetTowers(0);
        RunTower(12.51f, d1);
        RunTower(12.51f, d2);
        (d1, d2) = state.GetTowers(1);
        RunTower(22.53f, d1);
        RunTower(22.53f, d2);
        (d1, d2) = state.GetTowers(2);
        RunTower(33.56f, d1);
        RunTower(33.56f, d2);
        (d1, d2) = state.GetTowers(3);
        RunTower(43.58f, d1);
        RunTower(43.58f, d2);
        (d1, d2) = state.GetTowers(4);
        RunTower(54.61f, d1);
        RunTower(54.61f, d2);
        (d1, d2) = state.GetTowers(5);
        RunTower(64.63f, d1);
        RunTower(64.63f, d2);
        (d1, d2) = state.GetTowers(6);
        RunTower(75.67f, d1);
        RunTower(75.67f, d2);
        (d1, d2) = state.GetTowers(7);
        RunTower(85.68f, d1);
        RunTower(85.68f, d2);
    }

    private void Run_OtherDebuffs()
    {
        
        world.Events.Add(11.04f, () => party.ForEachActive(p => p.AddStatus(StatusId.SpellsTrouble, duration: 999f, stacks: (ushort)4, overrideStacks: true)));
        world.Events.Add(11.04f, () => party.ForEachActive(p => p.AddStatus(StatusId.Unknown13DC)));
    }

    private void Run_PlayerLockons()
    {
        world.Events.Add(11.04f, () => party.ForEachActive(c => c.AttachLockonVfx(state.Lockons[((ISimPartyMember)c).Role], persistent: false))); 
    }

    public void Tick(float delta, float elapsed) { }
    
    private void Run_Kefka_40004FD3()
    {
        SimEnemy? kefka_40004FD3 = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: BNpcBaseId.GodKefka, NameId: BNpcNameId.Kefka, Level: 100, Targetable: true, EnemyList: EnemyListMode.Always, IsVisible: true, Placement: new Placement(new Vector3(0.000f, 0.000f, 0.000f), 0.000f)));
        world.Events.Add(1.0f, () => kefka_40004FD3?.Face(party.Get(PartyRole.OffTank)));
        world.Events.Add(1.30f, () => kefka_40004FD3?.Cast(ActionId.AutoAttack1, castSeconds: 0f, targetId: party.Get(PartyRole.OffTank)?.GameObjectId));
        world.Events.Add(2.46f, () => kefka_40004FD3?.Cast(ActionId.Forsaken));
        world.Events.Add(9.43f, () => world.SetWeather(89));
        
        world.Events.Add(11.15f, () => kefka_40004FD3?.Face(party.Get(PartyRole.OffTank)));
        world.Events.Add(11.35f, () => kefka_40004FD3?.Cast(ActionId.AutoAttack1, castSeconds: 0f, targetId: party.Get(PartyRole.OffTank)?.GameObjectId));
        world.Events.Add(14.09f, () => kefka_40004FD3?.Face(party.Get(PartyRole.OffTank)));
        world.Events.Add(14.39f, () => kefka_40004FD3?.Cast(ActionId.AutoAttack1, castSeconds: 0f, targetId: party.Get(PartyRole.OffTank)?.GameObjectId));
        world.Events.Add(17.13f, () => kefka_40004FD3?.Face(party.Get(PartyRole.OffTank)));
        world.Events.Add(17.43f, () => kefka_40004FD3?.Cast(ActionId.AutoAttack1, castSeconds: 0f, targetId: party.Get(PartyRole.OffTank)?.GameObjectId));
        world.Events.Add(20.17f, () => kefka_40004FD3?.Face(party.Get(PartyRole.OffTank)));
        world.Events.Add(20.47f, () => kefka_40004FD3?.Cast(ActionId.AutoAttack1, castSeconds: 0f, targetId: party.Get(PartyRole.OffTank)?.GameObjectId));
        world.Events.Add(13.21f, () => kefka_40004FD3?.Face(party.Get(PartyRole.OffTank)));
        world.Events.Add(23.51f, () => kefka_40004FD3?.Cast(ActionId.AutoAttack1, castSeconds: 0f, targetId: party.Get(PartyRole.OffTank)?.GameObjectId));
        
        RunKefkaEndAttack(kefka_40004FD3, 0, 25.61f);
        RunKefkaEndAttack(kefka_40004FD3, 1, 46.52f);
        RunKefkaEndAttack(kefka_40004FD3, 2, 67.39f);
        RunKefkaEndAttack(kefka_40004FD3, 3, 88.36f);
        
        world.Events.Add(109.17f, () => kefka_40004FD3?.Face(party.Get(PartyRole.OffTank)));
        world.Events.Add(109.47f, () => kefka_40004FD3?.Cast(ActionId.AutoAttack1, castSeconds: 0f, targetId: party.Get(PartyRole.OffTank)?.GameObjectId));
        world.Events.Add(110.58f, () => kefka_40004FD3?.Cast(ActionId.LightOfJudgment));
    }
    
   private IReadOnlyList<SimCharacter> EndAttackTargets = [];
    
    private void RunKefkaEndAttack(SimEnemy? kefka_40004FD3, int index, float start)
    {
        var end = state.EndAttacks[index];
        world.Events.Add(start, () => kefka_40004FD3?.Cast(end.CastBarAction));
        world.Events.Add(start + 6.7f, () =>
        {
            if (kefka_40004FD3 == null) return;
            EndAttackTargets = party.Find.ClosestN(kefka_40004FD3.Position, 4);
            var target = EndAttackTargets.Count > 0 ? EndAttackTargets[0] : null;
            kefka_40004FD3?.Cast(end.KefkaResolveAction, castSeconds: 0f, targetId: target?.GameObjectId);
            damage.Resolve(target, end.KefkaResolveAction, [DamageType.Magic], [(StatusId.MagicVulnerabilityUp, 1.96f)]);
        });
        world.Events.Add(start + 12.8f, () => kefka_40004FD3?.Face(party.Player));
        world.Events.Add(start + 12.9f, () => kefka_40004FD3?.Cast(end.AllThingsEnding, targetLocation: party.Player!.Position));
        world.Events.Add(start + 17.9f, () => damage.Resolve(kefka_40004FD3, end.AllThingsEnding, [DamageType.Lethal], [], size: Geometry.AllThingsEndHalfCone, coneRotationDelta: end.RotationOverride));
    }

    private void RunTower(SimEnemy? enemy1, SimEnemy? enemy2, float start, int index)
    {
        Direction d1, d2;
        (d1, d2) = state.GetTowers(index);
        world.Events.Add(start - 1f, () => enemy1?.SetPosition(d1.Apply(new Placement(new Vector3(0.000f, 0.000f, -8.000f), 0))));
        world.Events.Add(start - 1f, () => enemy2?.SetPosition(d2.Apply(new Placement(new Vector3(0.000f, 0.000f, -8.000f), 0))));
        world.Events.Add(start, () =>
        {
            if (enemy1 == null || enemy2 == null) return;
            var targets1 = damage.Resolve(enemy1, ActionId.ThePathOfLight, [], []);
            if (targets1.Count == 2)
            {
                enemy1?.Cast(ActionId.ThePathOfLight);
                ResolveTower(targets1[0], 0);
                ResolveTower(targets1[1], 1);
            }
            else
            {
                enemy1?.Cast(ActionId.TheRiverOfLight);
                party.WipeAllPlayers($"Unresolved 2-enumeration tower: {targets1.Count} targets in tower");               
            }
            
            var targets2 = damage.Resolve(enemy2, ActionId.ThePathOfLight, [], []);
            if (targets2.Count == 2)
            {
                enemy2?.Cast(ActionId.ThePathOfLight);
                ResolveTower(targets2[0], 2);
                ResolveTower(targets2[1], 3);
            }
            else
            {
                enemy2?.Cast(ActionId.TheRiverOfLight);
                party.WipeAllPlayers($"Unresolved 2-enumeration tower: {targets2.Count} targets in tower");               
            }
            if (targets2.Count == 2 && targets1.Count == 2)
            {
                ReapplyLockons([targets1[0], targets1[1], targets2[0], targets2[1]], index);
            }
        });
    }
    
    private void ReapplyLockons(SimCharacter[] characters, int index)
    {
       var list = characters.Shuffle().ToList();
       uint[] lockons = index switch
       {
           6 => [LockonId.ForsakenStack, LockonId.ForsakenStack, LockonId.ForsakenCone, LockonId.ForsakenStack],
           _ when index % 2 == 0 => [LockonId.ForsakenCone, LockonId.ForsakenCone, LockonId.ForsakenChariot, LockonId.ForsakenChariot], 
           _ when index % 2 == 1 => [LockonId.ForsakenStack, LockonId.ForsakenStack, LockonId.ForsakenCone, LockonId.ForsakenChariot],
           _ => throw new ArgumentOutOfRangeException(nameof(index), index, null)
       };
       String s = "";
       for (int i = 0; i < 4; i++)
       {
           list[i].AddStatus(StatusId.SpellsTrouble, duration: 999f, stacks: -1);
           var role = (list[i] as ISimPartyMember)!.Role;
           if (list[i].HasStatus(StatusId.SpellsTrouble))
           {
               list[i].AttachLockonVfx(lockons[i], persistent: false);
               state.Lockons[role] = lockons[i];
               s += $"{role}={lockons[i]},";
           }
           else 
           {
               state.Lockons[role] = 0;
               s += $"{role}=0,";
           }
       }
       Plugin.Log.Info($"Lockons reassignment {s}");
    }
    
    private void ResolveTower(SimCharacter character, int index)
    {
        var position = character.Placement();
        var closest = party.Find.Closest(character.Position, character);
        if (closest != null) position = position.Face(closest.Position);
        towerHelper[index]?.SetPosition(position);
        var lockon = state.Lockons[((ISimPartyMember)character).Role];
        world.Events.Add(0.5f, () =>
        {
            if (towerHelper[index]?.Placement() != position)
                Plugin.Log.Warning($"tower helper position changed from {position} to {towerHelper[index]?.Placement()}");
            towerHelper[index]?.SetPosition(position);
            switch (lockon)
            {
                case LockonId.ForsakenStack:
                    towerHelper[index]?.Cast(ActionId.Spelldriver);
                    damage.Resolve(towerHelper[index], ActionId.Spelldriver, [DamageType.Magic], [(StatusId.MagicVulnerabilityUp, 1.96f)], stackMinTargets: 3);
                    break;
                case LockonId.ForsakenChariot:
                    towerHelper[index]?.Cast(ActionId.Spellscatter);
                    damage.Resolve(towerHelper[index], ActionId.Spellscatter, [DamageType.Magic], [(StatusId.MagicVulnerabilityUp, 1.96f)]);
                    break;
                case LockonId.ForsakenCone:
                    towerHelper[index]?.Cast(ActionId.Spellwave);
                    damage.Resolve(towerHelper[index], ActionId.Spellwave, [DamageType.Magic], [(StatusId.MagicVulnerabilityUp, 1.96f)], size: MathF.PI / 4, excludeTargets: [character]);
                    break;
            }
        });
    }
    
   private readonly List<SimEnemy?> towerHelper = [];
    
    private void Run_Kefka_40004FAC()
    {
        SimEnemy? towerHelper1 = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: BNpcBaseId.KefkaHelper, NameId: BNpcNameId.Kefka, Level: 1, Targetable: false, EnemyList: EnemyListMode.Never, IsVisible: false, Placement: new Placement(new Vector3(0.000f, 0.000f, -10.000f), 0.000f)));
        SimEnemy? towerHelper2 = world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: BNpcBaseId.KefkaHelper, NameId: BNpcNameId.Kefka, Level: 1, Targetable: false, EnemyList: EnemyListMode.Never, IsVisible: false, Placement: new Placement(new Vector3(0.000f, 0.000f, -10.000f), 0.000f)));
        RunTower(towerHelper1, towerHelper2, 22.66f, 0);
        RunTower(towerHelper1, towerHelper2, 32.67f, 1);
        RunTower(towerHelper1, towerHelper2, 43.71f, 2);
        RunTower(towerHelper1, towerHelper2, 53.72f, 3);
        RunTower(towerHelper1, towerHelper2, 64.76f, 4);
        RunTower(towerHelper1, towerHelper2, 74.77f, 5);
        RunTower(towerHelper1, towerHelper2, 85.81f, 6);
        RunTower(towerHelper1, towerHelper2, 95.82f, 7);
        
        towerHelper.Clear();
        for (int i = 0; i < 4; i++)
        {
            towerHelper.Add(world.SpawnEnemy(new EnemySpawnConfig(BNpcBaseId: BNpcBaseId.KefkaHelper, NameId: BNpcNameId.Kefka, Level: 1, Targetable: false, EnemyList: EnemyListMode.Never, IsVisible: false, Placement: new Placement(new Vector3(0.000f, 0.000f, -10.000f), 0.000f))));
        }
    }
    
    // Based on logs, clones end up 4y away from their target
    // TODO: verify in simulator
    private void RunCloneEndAttack(SimEnemy? enemy, float start, int number, int index)
    {
        var end = state.EndAttacks[number];
        world.Events.Add(start - 0.5f, () => enemy?.SetPosition(new Vector3(0, 0, 0)));
        world.Events.Add(start - 0.2f, () => enemy?.SetVisible(true));
        world.Events.Add(start, () =>
        {
            var target = EndAttackTargets.Count > index + 1 ? EndAttackTargets[index + 1] : null;
            enemy?.Cast(end.CloneResolveAction, castSeconds: 0f, targetId: target?.GameObjectId);
            damage.Resolve(target, end.CloneResolveAction, [DamageType.Magic], [(StatusId.MagicVulnerabilityUp, 1.96f)]);
            
        });
        world.Events.Add(start + 6f, () => enemy?.Face(party.Player));
        world.Events.Add(start + 6.1f, () => enemy?.Cast(end.AllThingsEnding, targetLocation: party.Player!.Position));
        world.Events.Add(start + 11.1f, () => damage.Resolve(enemy, end.AllThingsEnding, [DamageType.Lethal], [], size: Geometry.AllThingsEndHalfCone, coneRotationDelta: end.RotationOverride));
        world.Events.Add(start + 14.1f, () => enemy?.PlayActionTimeline(TimelineId.WarpOut));
    }

    
    private void Run_Kefka_40004FD0()
    {
        for (int i = 0; i < 3; i++)
        {
            SimEnemy? kefka_40004FD0 = world.SpawnEnemy(new EnemySpawnConfig(HitboxRadius: 3.5f + 0.2f, BNpcBaseId: BNpcBaseId.KefkaClone, NameId: BNpcNameId.Kefka, Level: 100, Targetable: false, EnemyList: EnemyListMode.Never, IsVisible: false, Placement: new Placement(new Vector3(0.000f, 0.000f, 0.000f), 0.000f)));
            RunCloneEndAttack(kefka_40004FD0, 32.35f, 0, i);
            RunCloneEndAttack(kefka_40004FD0, 53.36f, 1, i);
            RunCloneEndAttack(kefka_40004FD0, 74.24f, 2, i);
            RunCloneEndAttack(kefka_40004FD0, 95.06f, 3, i);
        }
    }
}
